/* ============================================================
   fronted-v2 / catalog.js
   templates/ 内の各 WebAPI 紹介ページ(HTML)のメタデータ一覧。
   この配列が「一覧の唯一の定義元」。テンプレートを追加したら
   ここに1要素足すだけでサイドバーに反映される。

   テンプレートはジャンル別のサブフォルダに整理されている:
     templates/image/  画像・ビジュアル系
     templates/data/   データ・検索系
     templates/tools/  為替・ツール系
     templates/fun/    エンタメ・おもしろ系

   各要素のフィールド:
     id          … URLハッシュ・選択識別子に使う一意キー（ファイル名ベース）
     file        … templates/ からの相対パス（例 "image/dog-api.html"）。
                    iframe は ../templates/<file> を読む
     title       … サイドバー/ヘッダーに表示する名称
     category    … 旧形式のグループ名（後方互換用）
     categoryPath… サイドバーの階層分類（例 ["データ・検索系", "宇宙・天気"]）
     description … ヘッダーのサブテキスト（このページの説明）
     apiName     … 利用している外部API名
     apiUrl      … 関連する公式ページ（参考リンク）
     icon        … Tabler Icons のクラス名（例 "ti-dog"）
   ============================================================ */

window.CATALOG = [
  /* ---------- 画像・ビジュアル系（動物・キャラ・画像を取得） ---------- */
  { id: "3d", file: "image/3D.html", title: "多ジャンル3Dモデル召喚API", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "3D・アバター"],
    description: "ランダムな3Dモデルを読み込み、回転操作しながら閲覧できる", apiName: "Three.js GLTF サンプル", apiUrl: "https://threejs.org/", icon: "ti-cube" },
  { id: "dog-api", file: "image/dog-api.html", title: "Dog API", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "ランダムな犬の画像を取得。犬種フィルターも搭載", apiName: "Dog API", apiUrl: "https://dog.ceo/dog-api/", icon: "ti-dog" },
  { id: "axolotl", file: "image/axolotl.html", title: "ウーパールーパー図鑑", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "Axolotl API から写真と豆知識を取得して表示", apiName: "Axolotl API", apiUrl: "https://theaxolotlapi.netlify.app/", icon: "ti-paw" },
  { id: "cataas", file: "image/cataas.html", title: "Cataas Cat Studio", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "Cataas の猫画像をランダム表示", apiName: "Cataas", apiUrl: "https://cataas.com/", icon: "ti-cat" },
  { id: "http-dog", file: "image/http-dog.html", title: "HTTP Dog Viewer", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "HTTP・ステータス画像"],
    description: "HTTPステータスコードを犬画像で表示", apiName: "HTTP Dog", apiUrl: "https://http.dog/", icon: "ti-dog" },
  { id: "placebear", file: "image/placebear.html", title: "PlaceBear Preview", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "指定サイズのクマ画像プレースホルダーを表示", apiName: "PlaceBear", apiUrl: "https://placebear.com/", icon: "ti-paw" },
  { id: "placedog", file: "image/placedog.html", title: "PlaceDog Preview", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "指定サイズの犬画像プレースホルダーを表示", apiName: "PlaceDog", apiUrl: "https://place.dog", icon: "ti-dog" },
  { id: "randomdog", file: "image/randomdog.html", title: "RandomDog Viewer", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "RandomDog の犬画像・動画URLをランダム表示", apiName: "RandomDog", apiUrl: "https://random.dog/woof.json", icon: "ti-dog" },
  { id: "shibe-online", file: "image/shibe-online.html", title: "Shibe Online", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "柴犬・猫・鳥のランダム画像を表示", apiName: "Shibe.Online", apiUrl: "http://shibe.online/", icon: "ti-dog" },
  { id: "cat-api", file: "image/cat-api.html", title: "The Cat API", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "ランダムな猫の画像と猫種データを取得", apiName: "The Cat API", apiUrl: "https://thecatapi.com/", icon: "ti-cat" },
  { id: "fox", file: "image/Fox.html", title: "Random Fox", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "ランダムなキツネの画像を取得", apiName: "RandomFox", apiUrl: "https://randomfox.ca/", icon: "ti-paw" },
  { id: "neko", file: "image/neko.html", title: "HTTP Cat", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "HTTP・ステータス画像"],
    description: "HTTPステータスコードを猫の画像で表示", apiName: "HTTP Cat", apiUrl: "https://http.cat/", icon: "ti-browser" },
  { id: "necos", file: "image/Necos.html", title: "Nekos.best", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "キャラクター画像"],
    description: "アニメ風のネコミミ画像ビューア", apiName: "Nekos.best", apiUrl: "https://nekos.best/", icon: "ti-mood-smile" },
  { id: "waifu", file: "image/Waifu.html", title: "Waifu Gallery", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "キャラクター画像"],
    description: "アニメキャラ画像のギャラリー", apiName: "Waifu.im", apiUrl: "https://waifu.im/", icon: "ti-sparkles" },
  { id: "catboys", file: "image/catboys.html", title: "Catboys", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "キャラクター画像"],
    description: "Catboys の画像と fact をまとめて取得", apiName: "Catboys API", apiUrl: "https://catboys.com/api", icon: "ti-mood-smile" },
  { id: "waifu-pics", file: "image/waifu-pics.html", title: "Waifu.pics", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "キャラクター画像"],
    description: "SFW の waifu / neko 画像をランダム表示", apiName: "Waifu.pics", apiUrl: "https://waifu.pics/docs", icon: "ti-sparkles" },
  { id: "kamo", file: "image/kamo.html", title: "アヒルで一息", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "ランダムなアヒルの画像で気分転換", apiName: "Random-d.uk", apiUrl: "https://random-d.uk/", icon: "ti-feather" },
  { id: "food", file: "image/food.html", title: "食べ物画像検索", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "食べ物画像"],
    description: "料理名でWikipediaの画像を検索して表示", apiName: "Wikipedia API", apiUrl: "https://www.mediawiki.org/wiki/API:Main_page", icon: "ti-tools-kitchen-2" },
  { id: "artic", file: "image/artic.html", title: "Art Institute Explorer", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "アート・デザイン"],
    description: "シカゴ美術館の公開作品を検索して画像付きで表示", apiName: "Art Institute of Chicago API", apiUrl: "https://api.artic.edu/docs/", icon: "ti-search" },
  { id: "colormind", file: "image/colormind.html", title: "Colormind Palette Lab", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "アート・デザイン"],
    description: "AIカラーパレットを生成して配色を確認", apiName: "Colormind", apiUrl: "http://colormind.io/api-access/", icon: "ti-palette" },
  { id: "colourlovers", file: "image/colourlovers.html", title: "ColourLovers Palettes", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "アート・デザイン"],
    description: "人気パレットの色見本を表示", apiName: "ColourLovers", apiUrl: "http://www.colourlovers.com/api", icon: "ti-palette" },
  { id: "dummyimage", file: "image/dummyimage.html", title: "DummyImage Maker", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "アート・デザイン"],
    description: "サイズと色を指定してダミー画像を生成", apiName: "DummyImage", apiUrl: "https://dummyimage.com/", icon: "ti-photo" },
  { id: "emojihub", file: "image/emojihub.html", title: "EmojiHub Picker", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "アート・デザイン"],
    description: "カテゴリ付きの絵文字データをランダム取得", apiName: "EmojiHub", apiUrl: "https://github.com/cheatsnake/emojihub", icon: "ti-mood-smile" },
  { id: "icon-horse", file: "image/icon-horse.html", title: "Icon Horse Favicon", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "アート・デザイン"],
    description: "ドメイン名からファビコンを取得", apiName: "Icon Horse", apiUrl: "https://icon.horse", icon: "ti-world" },
  { id: "icons8", file: "image/icons8.html", title: "Icons8 CDN Preview", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "アート・デザイン"],
    description: "Icons8 CDN のアイコンURLを組み立てて表示", apiName: "Icons8", apiUrl: "https://img.icons8.com/", icon: "ti-icons" },
  { id: "lordicon", file: "image/lordicon.html", title: "Lordicon Motion Icons", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "アート・デザイン"],
    description: "Lordicon のアニメーションアイコンをプレビュー", apiName: "Lordicon", apiUrl: "https://lordicon.com/", icon: "ti-sparkles" },
  { id: "metmuseum", file: "image/metmuseum.html", title: "Met Museum Search", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "アート・デザイン"],
    description: "メトロポリタン美術館の作品を検索して表示", apiName: "Metropolitan Museum of Art Collection API", apiUrl: "https://metmuseum.github.io/", icon: "ti-search" },
  { id: "php-noise", file: "image/php-noise.html", title: "PHP Noise Studio", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "アート・デザイン"],
    description: "ノイズ背景のパターンを生成して確認", apiName: "PHP-Noise", apiUrl: "https://php-noise.com/", icon: "ti-photo" },
  { id: "pixel-encounter", file: "image/pixel-encounter.html", title: "Pixel Encounter Generator", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "アート・デザイン"],
    description: "ピクセル風モンスターSVGをランダム生成", apiName: "Pixel Encounter", apiUrl: "https://pixelencounter.com/api", icon: "ti-device-gamepad-2" },
  { id: "xcolors", file: "image/xcolors.html", title: "xColors Palette", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "アート・デザイン"],
    description: "ランダムカラーと補色系の配色を取得", apiName: "xColors", apiUrl: "https://x-colors.herokuapp.com/", icon: "ti-palette" },  { id: "dance-proto", file: "image/dance-proto.html", title: "Dance Prototype", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "3D・アバター"],
    description: "GLTFモデルを読み込み、アニメーションを切り替えて再生", apiName: "Three.js GLTF サンプル", apiUrl: "https://threejs.org/", icon: "ti-cube" },
  { id: "oto", file: "image/oto.html", title: "Avatar Studio", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "3D・アバター"],
    description: "3DアバターにBGMとTTSを組み合わせたダンスビューア", apiName: "Three.js / Web Speech API", apiUrl: "https://threejs.org/", icon: "ti-sparkles" },

  /* ---------- データ・検索系（一覧/検索/詳細データを扱う） ---------- */
  { id: "cat-facts-legacy", file: "data/cat-facts-legacy.html", title: "Cat Facts Archive", category: "データ・検索系", categoryPath: ["データ・検索系", "動物データ"],
    description: "猫に関する豆知識をランダム表示", apiName: "Cat Facts", apiUrl: "https://alexwohlbruck.github.io/cat-facts/", icon: "ti-cat" },
  { id: "catfact-ninja", file: "data/catfact-ninja.html", title: "CatFact Ninja", category: "データ・検索系", categoryPath: ["データ・検索系", "動物データ"],
    description: "CatFact Ninja から猫の豆知識を取得", apiName: "CatFact Ninja", apiUrl: "https://catfact.ninja/", icon: "ti-cat" },
  { id: "dog-facts-duke", file: "data/dog-facts-duke.html", title: "Dog Facts Classic", category: "データ・検索系", categoryPath: ["データ・検索系", "動物データ"],
    description: "犬の豆知識をランダム表示", apiName: "Dog Facts API", apiUrl: "https://dukengn.github.io/Dog-facts-API/", icon: "ti-dog" },
  { id: "dog-facts-kinduff", file: "data/dog-facts-kinduff.html", title: "Dog API Facts", category: "データ・検索系", categoryPath: ["データ・検索系", "動物データ"],
    description: "Dog API から犬の豆知識を取得", apiName: "Dog API", apiUrl: "https://kinduff.github.io/dog-api/", icon: "ti-dog" },
  { id: "fishwatch", file: "data/fishwatch.html", title: "FishWatch Species", category: "データ・検索系", categoryPath: ["データ・検索系", "動物データ"],
    description: "FishWatch の魚種情報と画像を表示", apiName: "FishWatch", apiUrl: "https://www.fishwatch.gov/developers", icon: "ti-search" },
  { id: "meowfacts", file: "data/meowfacts.html", title: "MeowFacts", category: "データ・検索系", categoryPath: ["データ・検索系", "動物データ"],
    description: "猫の豆知識を取得", apiName: "MeowFacts", apiUrl: "https://github.com/wh-iterabb-it/meowfacts", icon: "ti-cat" },
  { id: "movebank", file: "data/movebank.html", title: "Movebank Explorer", category: "データ・検索系", categoryPath: ["データ・検索系", "動物データ"],
    description: "動物の移動研究データAPIを紹介", apiName: "Movebank API", apiUrl: "https://github.com/movebank/movebank-api-doc", icon: "ti-map" },
  { id: "rescuegroups", file: "data/rescuegroups.html", title: "RescueGroups Guide", category: "データ・検索系", categoryPath: ["データ・検索系", "動物データ"],
    description: "保護動物・里親募集データAPIの概要", apiName: "RescueGroups API", apiUrl: "https://userguide.rescuegroups.org/display/APIDG/API+Developers+Guide+Home", icon: "ti-paw" },
  { id: "xeno-canto", file: "data/xeno-canto.html", title: "xeno-canto Bird Calls", category: "データ・検索系", categoryPath: ["データ・検索系", "動物データ"],
    description: "野鳥の録音データを検索して再生", apiName: "xeno-canto", apiUrl: "https://xeno-canto.org/explore/api", icon: "ti-search" },
  { id: "anime", file: "data/anime.html", title: "アニメ図鑑", category: "データ・検索系", categoryPath: ["データ・検索系", "アニメ・カード"],
    description: "アニメをキーワード検索・ランキング表示", apiName: "Jikan API", apiUrl: "https://jikan.moe/", icon: "ti-movie" },
  { id: "jikan", file: "data/Jikan.html", title: "アニメ掲示板", category: "データ・検索系", categoryPath: ["データ・検索系", "アニメ・カード"],
    description: "アニメ情報を掲示板風に一覧表示", apiName: "Jikan API", apiUrl: "https://jikan.moe/", icon: "ti-message-circle" },
  { id: "anime-news-network", file: "data/anime-news-network.html", title: "Anime News Network", category: "データ・検索系", categoryPath: ["データ・検索系", "アニメ・カード"],
    description: "ANN のアニメ記事・レポート見出しを一覧表示", apiName: "Anime News Network Encyclopedia API", apiUrl: "https://www.animenewsnetwork.com/encyclopedia/api.php", icon: "ti-article" },
  { id: "ghibli", file: "data/ghibli.html", title: "Studio Ghibli", category: "データ・検索系", categoryPath: ["データ・検索系", "アニメ・カード"],
    description: "ジブリ作品一覧を選んで詳細を表示", apiName: "Studio Ghibli API", apiUrl: "https://ghibliapi.vercel.app/", icon: "ti-book" },
  { id: "trace-moe", file: "data/trace-moe.html", title: "trace.moe", category: "データ・検索系", categoryPath: ["データ・検索系", "アニメ・カード"],
    description: "画像URLからアニメの出典候補を検索", apiName: "trace.moe API", apiUrl: "https://soruly.github.io/trace.moe-api/", icon: "ti-search" },
  { id: "poke", file: "data/Poke.html", title: "ポケモンガチャ", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "ランダムにポケモンを引いて図鑑表示", apiName: "PokeAPI", apiUrl: "https://pokeapi.co/", icon: "ti-device-gamepad-2" },
  { id: "akusyonn", file: "data/akusyonn.html", title: "ゲーム図鑑", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "無料PCゲームの一覧・情報を取得", apiName: "FreeToGame", apiUrl: "https://www.freetogame.com/api-doc", icon: "ti-device-gamepad" },
  { id: "applemusic", file: "data/applemusic.html", title: "Apple Music 検索", category: "データ・検索系", categoryPath: ["データ・検索系", "音楽・書籍"],
    description: "iTunes の楽曲をキーワード検索", apiName: "iTunes Search API", apiUrl: "https://performance-partners.apple.com/search-api", icon: "ti-music" },
  { id: "nasa", file: "data/nasa.html", title: "NASA 今日の天体", category: "データ・検索系", categoryPath: ["データ・検索系", "宇宙・天気"],
    description: "NASA APOD の天体写真をランダム表示", apiName: "NASA APOD", apiUrl: "https://api.nasa.gov/", icon: "ti-rocket" },
  { id: "utyu", file: "data/utyu.html", title: "NASA 近地天体", category: "データ・検索系", categoryPath: ["データ・検索系", "宇宙・天気"],
    description: "地球近傍小惑星(NEO)の観測ダッシュボード", apiName: "NASA NeoWs", apiUrl: "https://api.nasa.gov/", icon: "ti-planet" },
  { id: "wakusei", file: "data/wakusei.html", title: "惑星情報", category: "データ・検索系", categoryPath: ["データ・検索系", "宇宙・天気"],
    description: "太陽系の惑星データを選んで表示（サンプル）", apiName: "ローカルデータ", apiUrl: "https://ja.wikipedia.org/wiki/惑星", icon: "ti-globe" },
  { id: "burogu", file: "data/burogu.html", title: "ランダム記事ローダー", category: "データ・検索系", categoryPath: ["データ・検索系", "記事・プロフィール"],
    description: "ダミーの記事データをランダムに読み込んで表示", apiName: "JSONPlaceholder", apiUrl: "https://jsonplaceholder.typicode.com/", icon: "ti-article" },
  { id: "game", file: "data/game.html", title: "高評価ゲーム一覧", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "評価の高いゲームを一覧表示（APIキー必要）", apiName: "RAWG API", apiUrl: "https://rawg.io/apidocs", icon: "ti-trophy" },
  { id: "amiibo", file: "data/amiibo.html", title: "Amiibo検索", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "Amiibo を名前やシリーズで検索して表示", apiName: "AmiiboAPI", apiUrl: "https://amiiboapi.com/", icon: "ti-user" },
  { id: "animal-crossing-new-horizons", file: "data/animal-crossing-new-horizons.html", title: "どうぶつの森 図鑑", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "住民や魚・虫・化石をカテゴリ別に検索", apiName: "Animal Crossing: New Horizons API", apiUrl: "http://acnhapi.com/", icon: "ti-cat" },
  { id: "astroworld", file: "data/astroworld.html", title: "Astroworld データベース", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "Minecraft系のモブやバイオームなどを検索", apiName: "Astroworld API", apiUrl: "https://api.astroworldmc.com/", icon: "ti-rocket" },
  { id: "autochess-vng", file: "data/autochess-vng.html", title: "Autochess VNG 図鑑", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "英雄・クラス・種族を切り替えて閲覧", apiName: "Autochess VNG API", apiUrl: "https://github.com/didadadida93/autochess-vng-api", icon: "ti-device-gamepad-2" },
  { id: "magic-the-gathering", file: "data/magic-the-gathering.html", title: "MTGカード検索", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "カード名でMTGカードを検索して一覧表示", apiName: "Magic The Gathering API", apiUrl: "http://magicthegathering.io/", icon: "ti-trophy" },
  { id: "minecraft-server-status", file: "data/minecraft-server-status.html", title: "Minecraft サーバー状態", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "Minecraftサーバーの状態とプレイヤー数を確認", apiName: "Minecraft Server Status API", apiUrl: "https://api.mcsrvstat.us/", icon: "ti-globe" },
  { id: "mmo-games", file: "data/mmo-games.html", title: "MMOゲーム一覧", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "MMOゲームの一覧・ニュース・配布情報を表示", apiName: "MMOBomb MMO Games API", apiUrl: "https://www.mmobomb.com/api", icon: "ti-device-gamepad-2" },
  { id: "monster-hunter-world", file: "data/monster-hunter-world.html", title: "モンハンワールド図鑑", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "モンスター一覧を検索して弱点と生息地を表示", apiName: "MHW DB API", apiUrl: "https://docs.mhw-db.com/", icon: "ti-trophy" },
  { id: "playerdb", file: "data/playerdb.html", title: "PlayerDB プロフィール検索", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "Minecraft / Steam / Xbox / Hytale のアカウントを検索", apiName: "PlayerDB", apiUrl: "https://playerdb.co/", icon: "ti-user" },
  { id: "hon", file: "data/hon.html", title: "現代漫画検索", category: "データ・検索系", categoryPath: ["データ・検索系", "音楽・書籍"],
    description: "キーワードで書籍・漫画を検索して表紙を表示", apiName: "Open Library", apiUrl: "https://openlibrary.org/developers/api", icon: "ti-book" },
  { id: "randomuser", file: "data/index.html", title: "ランダムユーザー生成器", category: "データ・検索系", categoryPath: ["データ・検索系", "記事・プロフィール"],
    description: "ランダムなプロフィール(氏名/写真/住所)を生成", apiName: "Random User Generator", apiUrl: "https://randomuser.me/", icon: "ti-user" },
  { id: "cars", file: "data/Cars.html", title: "Car Explorer", category: "データ・検索系", categoryPath: ["データ・検索系", "乗り物・交通"],
    description: "メーカーとモデルを選んで車両情報と画像を検索", apiName: "NHTSA Vehicle API / Wikipedia API", apiUrl: "https://vpic.nhtsa.dot.gov/api/", icon: "ti-car" },
  { id: "yugio", file: "data/Yugio.html", title: "遊戯王カード図鑑", category: "データ・検索系", categoryPath: ["データ・検索系", "アニメ・カード"],
    description: "カード名・属性・種族で検索してランダム表示", apiName: "YGOPRODeck API / MyMemory Translation API", apiUrl: "https://db.ygoprodeck.com/api-guide/", icon: "ti-cards" },
  { id: "countrysearch", file: "data/countrySearch.html", title: "国情報検索", category: "データ・検索系", categoryPath: ["データ・検索系", "国・地域"],
    description: "国名から人口と首都情報を検索して表示", apiName: "CountriesNow API", apiUrl: "https://countriesnow.space/", icon: "ti-globe" },
  { id: "domainsdb", file: "data/domainsdb.html", title: "DomainsDB Search", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "登録済みドメイン名をキーワード検索", apiName: "DomainsDB API", apiUrl: "https://domainsdb.info/", icon: "ti-search" },
  { id: "markerapi", file: "data/markerapi.html", title: "MarkerAPI Trademark Search", category: "データ・検索系", categoryPath: ["データ・検索系", "企業・公共データ"],
    description: "USPTO商標データを認証情報入力式で検索", apiName: "MarkerAPI", apiUrl: "https://markerapi.com", icon: "ti-search" },
  { id: "pick-an-agency", file: "data/pick-an-agency.html", title: "Pick an Agency Search", category: "データ・検索系", categoryPath: ["データ・検索系", "企業・公共データ"],
    description: "サービスと地域からマーケティング代理店を検索", apiName: "Pick an Agency API", apiUrl: "https://www.pickanagency.com/developers", icon: "ti-search" },
  { id: "tenders-guru-hu", file: "data/tenders-guru-hu.html", title: "Tenders Guru Hungary", category: "データ・検索系", categoryPath: ["データ・検索系", "企業・公共データ"],
    description: "ハンガリーの公共調達データをページ単位で取得", apiName: "Tenders Guru API", apiUrl: "https://tenders.guru/hu/api", icon: "ti-article" },
  { id: "tenders-guru-pl", file: "data/tenders-guru-pl.html", title: "Tenders Guru Poland", category: "データ・検索系", categoryPath: ["データ・検索系", "企業・公共データ"],
    description: "ポーランドの公共調達データをページ単位で取得", apiName: "Tenders Guru API", apiUrl: "https://tenders.guru/pl/api", icon: "ti-article" },
  { id: "tenders-guru-ro", file: "data/tenders-guru-ro.html", title: "Tenders Guru Romania", category: "データ・検索系", categoryPath: ["データ・検索系", "企業・公共データ"],
    description: "ルーマニアの公共調達データをページ単位で取得", apiName: "Tenders Guru API", apiUrl: "https://tenders.guru/ro/api", icon: "ti-article" },
  { id: "tenders-guru-es", file: "data/tenders-guru-es.html", title: "Tenders Guru Spain", category: "データ・検索系", categoryPath: ["データ・検索系", "企業・公共データ"],
    description: "スペインの公共調達データをページ単位で取得", apiName: "Tenders Guru API", apiUrl: "https://tenders.guru/es/api", icon: "ti-article" },
  { id: "tenders-guru-ua", file: "data/tenders-guru-ua.html", title: "Tenders Guru Ukraine", category: "データ・検索系", categoryPath: ["データ・検索系", "企業・公共データ"],
    description: "ウクライナの公共調達データをページ単位で取得", apiName: "Tenders Guru API", apiUrl: "https://tenders.guru/ua/api", icon: "ti-article" },
  { id: "ip", file: "data/ip.html", title: "IP Geolocation Dashboard", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "IP位置情報データをダッシュボード形式で表示（サンプル）", apiName: "ローカルサンプルデータ", apiUrl: "", icon: "ti-user" },
  { id: "food-hygiene-ratings", file: "data/food-hygiene-ratings.html", title: "食品衛生レーティング", category: "データ・検索系", categoryPath: ["データ・検索系", "食品・生活"],
    description: "食品衛生評価の公開データを地域別に探索", apiName: "Food Hygiene Ratings API", apiUrl: "https://ratings.food.gov.uk/open-data", icon: "ti-tools-kitchen-2" },
  { id: "inei-portal", file: "data/inei-portal.html", title: "INEI 統計ポータル", category: "データ・検索系", categoryPath: ["データ・検索系", "統計・公的データ"],
    description: "INEI のテーマ別統計リンクを検索・参照", apiName: "INEI 統計ポータル", apiUrl: "https://www.inei.gob.pe/estadisticas-indice-tematico/", icon: "ti-article" },
  { id: "interpol-red-notices", file: "data/interpol-red-notices.html", title: "Interpol 指名手配検索", category: "データ・検索系", categoryPath: ["データ・検索系", "事件・捜査"],
    description: "Interpol赤手配の人物を条件検索して表示", apiName: "Interpol Notices API", apiUrl: "https://interpol.api.bund.dev/", icon: "ti-search" },
  { id: "ibb-open-data", file: "data/ibb-open-data.html", title: "İBB オープンデータ", category: "データ・検索系", categoryPath: ["データ・検索系", "都市・オープンデータ"],
    description: "İBB公開データをキーワードとカテゴリで検索", apiName: "İBB Open Data Portal", apiUrl: "https://data.ibb.gov.tr/", icon: "ti-globe" },
  { id: "kabu", file: "data/kabu.html", title: "株価検索", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "銘柄コードを入力して株価と騰落率を取得", apiName: "Alpha Vantage", apiUrl: "https://www.alphavantage.co/documentation/", icon: "ti-currency-yen" },
  { id: "chainlink", file: "data/chainlink.html", title: "Chainlink Data Feeds", category: "データ・検索系", categoryPath: ["データ・検索系", "ブロックチェーン・市場"],
    description: "Chainlink のData Feeds種別と利用イメージを確認", apiName: "Chainlink Data Feeds", apiUrl: "https://docs.chain.link/data-feeds", icon: "ti-link" },
  { id: "chainpoint", file: "data/chainpoint.html", title: "Chainpoint Proof Guide", category: "データ・検索系", categoryPath: ["データ・検索系", "ブロックチェーン・市場"],
    description: "ハッシュを使ったブロックチェーン証明の流れを表示", apiName: "Chainpoint", apiUrl: "https://tierion.com/chainpoint/", icon: "ti-link" },
  { id: "helium", file: "data/helium.html", title: "Helium Network API", category: "データ・検索系", categoryPath: ["データ・検索系", "ブロックチェーン・市場"],
    description: "Heliumネットワーク情報APIの取得イメージを確認", apiName: "Helium API", apiUrl: "https://docs.helium.com/api/blockchain/introduction/", icon: "ti-antenna" },
  { id: "steem", file: "data/steem.html", title: "Steem JSON-RPC Market", category: "データ・検索系", categoryPath: ["データ・検索系", "ブロックチェーン・市場"],
    description: "SteemのJSON-RPCで内部マーケット情報を取得", apiName: "Steem JSON-RPC API", apiUrl: "https://developers.steem.io/", icon: "ti-article" },
  { id: "twzrd-agent-intel", file: "data/twzrd-agent-intel.html", title: "TWZRD Agent Intel", category: "データ・検索系", categoryPath: ["データ・検索系", "ブロックチェーン・市場"],
    description: "Solana上のAIエージェント信頼スコア取得をキー入力式で試す", apiName: "TWZRD Agent Intel", apiUrl: "https://intel.twzrd.xyz", icon: "ti-search" },
  { id: "walltime", file: "data/walltime.html", title: "Walltime Market Info", category: "データ・検索系", categoryPath: ["データ・検索系", "ブロックチェーン・市場"],
    description: "市場情報APIのレスポンスをカード形式で確認", apiName: "Walltime API", apiUrl: "https://walltime.info/api.html", icon: "ti-currency-yen" },
  { id: "zero-x", file: "data/zero-x.html", title: "0x API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "DEXの価格見積もりやスワップAPIを入力キー付きで確認", apiName: "0x API", apiUrl: "https://0x.org/api", icon: "ti-currency-yen" },
  { id: "one-inch", file: "data/one-inch.html", title: "1inch API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "1inchのDEX集約APIをBearerキー入力式で試す", apiName: "1inch API", apiUrl: "https://1inch.io/api/", icon: "ti-currency-yen" },
  { id: "alpha-mossland", file: "data/alpha-mossland.html", title: "Alpha by Mossland", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "韓国暗号資産チャンネル由来の正規化データを表示", apiName: "Alpha by Mossland", apiUrl: "https://alpha.moss.land/developers", icon: "ti-search" },
  { id: "bitcambio", file: "data/bitcambio.html", title: "Bitcambio Public API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "ブラジル取引所の公開アセット情報を確認", apiName: "Bitcambio API", apiUrl: "https://nova.bitcambio.com.br/api/v3/docs#a-public", icon: "ti-currency-yen" },
  { id: "bitcoincharts", file: "data/bitcoincharts.html", title: "BitcoinCharts Markets", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "BitcoinChartsのマーケット一覧JSONを表示", apiName: "BitcoinCharts", apiUrl: "https://bitcoincharts.com/about/exchanges/", icon: "ti-currency-yen" },
  { id: "block-lottos", file: "data/block-lottos.html", title: "Block Lottos OpenAPI", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "オンチェーン抽選サービスのOpenAPI定義を読む", apiName: "Block Lottos", apiUrl: "https://blocklottos.com/openapi.json", icon: "ti-trophy" },
  { id: "btcnode-uk", file: "data/btcnode-uk.html", title: "btcnode.uk", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Bitcoinデータやx402課金エンドポイントのURLを確認", apiName: "btcnode.uk", apiUrl: "https://btcnode.uk", icon: "ti-currency-yen" },
  { id: "coincap", file: "data/coincap.html", title: "CoinCap API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "暗号資産の価格・時価総額・取引所データを取得", apiName: "CoinCap", apiUrl: "https://docs.coincap.io/", icon: "ti-currency-yen" },
  { id: "coindesk-bpi", file: "data/coindesk-bpi.html", title: "CoinDesk BPI", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Bitcoin Price Index系JSONを確認", apiName: "CoinDesk BPI", apiUrl: "https://old.coindesk.com/coindesk-api/", icon: "ti-currency-yen" },
  { id: "coingecko", file: "data/coingecko.html", title: "CoinGecko API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "BTC/ETHの複数通貨建て価格を取得", apiName: "CoinGecko API", apiUrl: "http://www.coingecko.com/api", icon: "ti-currency-yen" },
  { id: "coinlore", file: "data/coinlore.html", title: "CoinLore API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "公開ティッカーAPIから価格・出来高を一覧表示", apiName: "CoinLore", apiUrl: "https://www.coinlore.com/cryptocurrency-data-api", icon: "ti-currency-yen" },
  { id: "coinpaprika", file: "data/coinpaprika.html", title: "Coinpaprika API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "暗号資産マーケットデータをティッカー形式で表示", apiName: "Coinpaprika", apiUrl: "https://api.coinpaprika.com", icon: "ti-currency-yen" },
  { id: "coinstats", file: "data/coinstats.html", title: "CoinStats API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "暗号資産トラッカーAPIをキー入力式で確認", apiName: "CoinStats", apiUrl: "https://documenter.getpostman.com/view/5734027/RzZ6Hzr3?version=latest", icon: "ti-currency-yen" },
  { id: "cryptapi", file: "data/cryptapi.html", title: "CryptAPI", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "暗号資産決済APIの公開情報エンドポイントを確認", apiName: "CryptAPI", apiUrl: "https://docs.cryptapi.io/", icon: "ti-currency-yen" },
  { id: "cryptingup", file: "data/cryptingup.html", title: "CryptingUp", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "取引ペアやマーケットデータを取得", apiName: "CryptingUp", apiUrl: "https://www.cryptingup.com/apidoc/#introduction", icon: "ti-currency-yen" },
  { id: "cryptocompare", file: "data/cryptocompare.html", title: "CryptoCompare", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "BTC/ETHの価格を複数通貨で比較", apiName: "CryptoCompare", apiUrl: "https://www.cryptocompare.com/api#", icon: "ti-currency-yen" },
  { id: "cryptonator", file: "data/cryptonator.html", title: "Cryptonator", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "暗号資産為替レートAPIを確認", apiName: "Cryptonator", apiUrl: "https://www.cryptonator.com/api/", icon: "ti-currency-yen" },
  { id: "gemini", file: "data/gemini.html", title: "Gemini REST API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Gemini取引所の公開マーケットデータを取得", apiName: "Gemini REST API", apiUrl: "https://docs.gemini.com/rest-api/", icon: "ti-currency-yen" },
  { id: "localbitcoins", file: "data/localbitcoins.html", title: "LocalBitcoins API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "旧P2P取引API資料とサンプルデータを確認", apiName: "LocalBitcoins", apiUrl: "https://localbitcoins.com/api-docs/", icon: "ti-currency-yen" },
  { id: "mempool-space", file: "data/mempool-space.html", title: "Mempool.space API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Bitcoinの推奨手数料を取得", apiName: "Mempool.space", apiUrl: "https://mempool.space/api", icon: "ti-currency-yen" },
  { id: "mercado-bitcoin", file: "data/mercado-bitcoin.html", title: "Mercado Bitcoin API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "BTC/BRLの公開ティッカーを確認", apiName: "Mercado Bitcoin", apiUrl: "https://www.mercadobitcoin.com.br/api-doc/", icon: "ti-currency-yen" },
  { id: "messari", file: "data/messari.html", title: "Messari API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Messariの暗号資産データAPIをキー入力式で確認", apiName: "Messari API", apiUrl: "https://messari.io/api", icon: "ti-currency-yen" },
  { id: "nexchange", file: "data/nexchange.html", title: "Nexchange API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "自動暗号資産交換サービスの通貨情報を確認", apiName: "Nexchange", apiUrl: "https://nexchange2.docs.apiary.io/", icon: "ti-currency-yen" },
  { id: "solana-json-rpc", file: "data/solana-json-rpc.html", title: "Solana JSON RPC", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Solana JSON-RPCへPOSTしてヘルスチェック", apiName: "Solana JSON RPC", apiUrl: "https://docs.solana.com/developing/clients/jsonrpc-api", icon: "ti-currency-yen" },
  { id: "zmok-ethereum-rpc", file: "data/zmok-ethereum-rpc.html", title: "ZMOK Ethereum RPC", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Ethereum JSON-RPCプロバイダーURLを入力して確認", apiName: "ZMOK", apiUrl: "https://zmok.io", icon: "ti-currency-yen" },
  { id: "radar", file: "data/radar.html", title: "ADS-B Flight Radar", category: "データ・検索系", categoryPath: ["データ・検索系", "乗り物・交通"],
    description: "地図範囲内の航空機データを取得して可視化", apiName: "OpenSky Network API", apiUrl: "https://opensky-network.org/apidoc/rest.html", icon: "ti-rocket" },
  { id: "saiba", file: "data/saiba-.html", title: "Shodan Intelligence Terminal", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "IPアドレスの公開情報と開放ポートを調査", apiName: "Shodan API", apiUrl: "https://developer.shodan.io/api", icon: "ti-browser" },
  { id: "urlhaus", file: "data/urlhaus.html", title: "URLhaus Intelligence", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "URLhaus の recent URLs / payloads を Auth-Key 付きで閲覧", apiName: "URLhaus API", apiUrl: "https://urlhaus-api.abuse.ch/", icon: "ti-search" },
  { id: "seibetu", file: "data/seibetu.html", title: "名前から性別を自動判別", category: "データ・検索系", categoryPath: ["データ・検索系", "人名・属性推定"],
    description: "ローマ字名から性別と確率を推定して表示", apiName: "Genderize.io", apiUrl: "https://genderize.io/", icon: "ti-user" },
  { id: "agify", file: "data/agify.html", title: "Agify.io 年齢推定", category: "データ・検索系", categoryPath: ["データ・検索系", "人名・属性推定"],
    description: "名前と国コードから推定年齢と参照件数を取得", apiName: "Agify.io", apiUrl: "https://agify.io/", icon: "ti-user" },
  { id: "weather", file: "data/weather.html", title: "天気アプリ（気象庁版）", category: "データ・検索系", categoryPath: ["データ・検索系", "宇宙・天気"],
    description: "都道府県名から最新の天気予報を取得", apiName: "気象庁 予報JSON", apiUrl: "https://www.jma.go.jp/bosai/forecast/", icon: "ti-planet" },
  { id: "24-pull-requests", file: "data/24-pull-requests.html", title: "24 Pull Requests Explorer", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "OSS貢献促進サービスのプロジェクト一覧やPR統計を取得", apiName: "24 Pull Requests API", apiUrl: "https://24pullrequests.com/api", icon: "ti-article" },
  { id: "api-gratis", file: "data/api-gratis.html", title: "API Grátis チェッカー", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "API Grátis公式URLの到達状況と仕様確認メモを表示", apiName: "API Grátis", apiUrl: "https://apigratis.com.br/", icon: "ti-search" },
  { id: "apicagent", file: "data/apicagent.html", title: "ApicAgent User-Agent 解析", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "User-Agent文字列を解析してブラウザ・OS・端末情報を表示", apiName: "ApicAgent", apiUrl: "https://www.apicagent.com/docs", icon: "ti-browser" },
  { id: "apis-guru", file: "data/apis-guru.html", title: "APIs.guru Directory Explorer", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "OpenAPIディレクトリのメトリクスとプロバイダ一覧を検索", apiName: "APIs.guru Directory API", apiUrl: "https://apis.guru/api-doc/", icon: "ti-search" },
  { id: "cdnjs", file: "data/cdnjs.html", title: "CDNJS Library Finder", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "cdnjsの公開APIからライブラリ情報とCDN URLを検索", apiName: "CDNJS API", apiUrl: "https://api.cdnjs.com/libraries/jquery", icon: "ti-search" },
  { id: "changelogs-md", file: "data/changelogs-md.html", title: "Changelogs.md Search", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "OSSライブラリのchangelog検索結果を取得して表示", apiName: "Changelogs.md", apiUrl: "https://changelogs.md", icon: "ti-article" },
  { id: "cloudflare-trace", file: "data/cloudflare-trace.html", title: "Cloudflare Trace Viewer", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "Cloudflare traceからIP・国・HTTP/TLS情報を取得", apiName: "Cloudflare Trace API", apiUrl: "https://github.com/fawazahmed0/cloudflare-trace-api", icon: "ti-browser" },
  { id: "digitalocean-status", file: "data/digitalocean-status.html", title: "DigitalOcean Status", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "DigitalOceanの全体状態とコンポーネント状態を取得", apiName: "DigitalOcean Status API", apiUrl: "https://status.digitalocean.com/api", icon: "ti-browser" },
  { id: "domainsdb", file: "data/domainsdb.html", title: "DomainDb Search", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "キーワードを含むドメイン名を検索", apiName: "DomainDb Info", apiUrl: "https://api.domainsdb.info/", icon: "ti-search" },
  { id: "downstatus", file: "data/downstatus.html", title: "DownStatus Monitor", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "外部サービスの稼働状況確認API候補を表示", apiName: "DownStatus", apiUrl: "https://isitdownstatus.com", icon: "ti-browser" },
  { id: "host-t-dns", file: "data/host-t-dns.html", title: "host-t DNS Query", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "HTTP GETでDNS問い合わせURLを作成し取得を試行", apiName: "host-t.com", apiUrl: "https://host-t.com", icon: "ti-globe" },
  { id: "icanhazip", file: "data/icanhazip.html", title: "Icanhazip Viewer", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "アクセス元のグローバルIPアドレスを取得", apiName: "Icanhazip", apiUrl: "https://major.io/icanhazip-com-faq/", icon: "ti-globe" },
  { id: "ip-fast", file: "data/ip-fast.html", title: "ip-fast Lookup", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "IPアドレス・国・都市情報を取得", apiName: "ip-fast.com", apiUrl: "https://ip-fast.com/docs/", icon: "ti-globe" },
  { id: "ipify", file: "data/ipify.html", title: "IPify Viewer", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "現在のグローバルIPアドレスをJSONで取得", apiName: "IPify", apiUrl: "https://www.ipify.org/", icon: "ti-globe" },
  { id: "ipinfo", file: "data/ipinfo.html", title: "IPinfo Lite", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "IPの地域・組織情報を取得（制限時はフォールバック）", apiName: "IPinfo", apiUrl: "https://ipinfo.io/developers", icon: "ti-globe" },
  { id: "my-ip", file: "data/my-ip.html", title: "MY IP Lookup", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "MY IP APIからIPアドレス情報を取得", apiName: "MY IP", apiUrl: "https://www.myip.com/api-docs/", icon: "ti-globe" },
  { id: "isitdownstatus", file: "data/isitdownstatus.html", title: "isitdownstatus Checker", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "Webサイトやサービスのダウン状態確認API候補", apiName: "isitdownstatus", apiUrl: "https://isitdownstatus.com", icon: "ti-browser" },
  { id: "jsdelivr", file: "data/jsdelivr.html", title: "jsDelivr Package Info", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "npmパッケージのCDNファイル情報を取得", apiName: "jsDelivr Data API", apiUrl: "https://github.com/jsdelivr/data.jsdelivr.com", icon: "ti-search" },
  { id: "license-api", file: "data/license-api.html", title: "License API Lookup", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "OSSライセンス情報API候補を取得またはフォールバック表示", apiName: "License-API", apiUrl: "https://github.com/cmccandless/license-api/blob/master/README.md", icon: "ti-article" },
  { id: "nationalize", file: "data/nationalize.html", title: "Nationalize.io Predictor", category: "データ・検索系", categoryPath: ["データ・検索系", "人名・属性推定"],
    description: "名前から国籍候補と確率を推定", apiName: "Nationalize.io", apiUrl: "https://nationalize.io", icon: "ti-user" },
  { id: "ai-dev-jobs", file: "data/ai-dev-jobs.html", title: "AI Dev Jobs API", category: "データ・検索系", categoryPath: ["データ・検索系", "求人・スキル"],
    description: "AI/MLエンジニア求人APIのOpenAPI定義を確認", apiName: "AI Dev Jobs", apiUrl: "https://aidevboard.com/openapi.yaml", icon: "ti-search" },
  { id: "arbeitnow", file: "data/arbeitnow.html", title: "Arbeitnow Job Board", category: "データ・検索系", categoryPath: ["データ・検索系", "求人・スキル"],
    description: "Europe/Remote求人をキーワードで絞り込んで表示", apiName: "Arbeitnow", apiUrl: "https://documenter.getpostman.com/view/18545278/UVJbJdKh", icon: "ti-article" },
  { id: "devitjobs-uk", file: "data/devitjobs-uk.html", title: "DevITjobs UK Feed", category: "データ・検索系", categoryPath: ["データ・検索系", "求人・スキル"],
    description: "UK開発者求人のXMLフィードを読み込んで表示", apiName: "DevITjobs UK", apiUrl: "https://devitjobs.uk/job_feed.xml", icon: "ti-article" },
  { id: "graphql-jobs", file: "data/graphql-jobs.html", title: "GraphQL Jobs API", category: "データ・検索系", categoryPath: ["データ・検索系", "求人・スキル"],
    description: "GraphQL求人APIへクエリをPOSTして確認", apiName: "GraphQL Jobs", apiUrl: "https://graphql.jobs/docs/api/", icon: "ti-search" },
  { id: "open-skills", file: "data/open-skills.html", title: "Open Skills API", category: "データ・検索系", categoryPath: ["データ・検索系", "求人・スキル"],
    description: "職種名やスキル名の候補を検索", apiName: "Open Skills", apiUrl: "https://github.com/workforce-data-initiative/skills-api/wiki/API-Overview", icon: "ti-user" },
  { id: "deepcode-ai", file: "data/deepcode-ai.html", title: "DeepCode AI", category: "データ・検索系", categoryPath: ["データ・検索系", "AI・機械学習"],
    description: "AIコードレビューサービスの公開情報を確認", apiName: "DeepCode AI", apiUrl: "https://www.deepcode.ai", icon: "ti-search" },
  { id: "exude-api", file: "data/exude-api.html", title: "EXUDE-API", category: "データ・検索系", categoryPath: ["データ・検索系", "AI・機械学習"],
    description: "英文テキストのストップワード除去を試す", apiName: "EXUDE-API", apiUrl: "http://uttesh.com/exude-api/", icon: "ti-language" },
  { id: "not-human-search", file: "data/not-human-search.html", title: "Not Human Search API", category: "データ・検索系", categoryPath: ["データ・検索系", "AI・機械学習"],
    description: "AIツール探索APIのOpenAPI定義を確認", apiName: "Not Human Search", apiUrl: "https://nothumansearch.ai/openapi.yaml", icon: "ti-search" },
  { id: "openvisionapi", file: "data/openvisionapi.html", title: "OpenVisionAPI", category: "データ・検索系", categoryPath: ["データ・検索系", "AI・機械学習"],
    description: "画像URLを渡すコンピュータビジョンAPIを確認", apiName: "OpenVisionAPI", apiUrl: "https://openvisionapi.com", icon: "ti-search" },
  { id: "tensorfeed", file: "data/tensorfeed.html", title: "TensorFeed API", category: "データ・検索系", categoryPath: ["データ・検索系", "AI・機械学習"],
    description: "AIニュース・モデル情報・サービス状態を取得", apiName: "TensorFeed", apiUrl: "https://tensorfeed.ai/developers", icon: "ti-article" },

  /* ---------- 為替・ツール系（実用ツール） ---------- */
  { id: "calendar", file: "tools/calendar.html", title: "カレンダー（祝日API付き）", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "祝日APIを参照して月間カレンダーを表示する", apiName: "Public Holidays API", apiUrl: "https://date.nager.at/", icon: "ti-calendar" },
  { id: "caldays", file: "tools/caldays.html", title: "CalDays 祝日API", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "APIキーを入力して国別の祝日データ取得を試す", apiName: "CalDays API", apiUrl: "https://caldays.com/api", icon: "ti-calendar" },
  { id: "church-calendar", file: "tools/church-calendar.html", title: "Church Calendar", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "指定日のカトリック典礼暦をJSONで確認", apiName: "Church Calendar API", apiUrl: "http://calapi.inadiutorium.cz/", icon: "ti-calendar" },
  { id: "czech-namedays", file: "tools/czech-namedays.html", title: "チェコ・スロバキア名前日", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "日付または名前からチェコ語・スロバキア語の名前日を検索", apiName: "Svátky API", apiUrl: "https://svatky.adresa.info", icon: "ti-calendar" },
  { id: "hebcal-converter", file: "tools/hebcal-converter.html", title: "Hebcal ヘブライ暦変換", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "グレゴリオ暦をヘブライ暦へ変換して表示", apiName: "Hebcal Developer APIs", apiUrl: "https://www.hebcal.com/home/developer-apis", icon: "ti-calendar" },
  { id: "lectserve", file: "tools/lectserve.html", title: "LectServe 朗読暦", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "プロテスタント系の朗読暦ページから見出しを抽出", apiName: "LectServe", apiUrl: "http://www.lectserve.com", icon: "ti-book" },
  { id: "nager-date", file: "tools/nager-date.html", title: "Nager.Date 世界祝日", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "国コードと年から世界各国の祝日一覧を取得", apiName: "Nager.Date", apiUrl: "https://date.nager.at", icon: "ti-calendar" },
  { id: "namedays-calendar", file: "tools/namedays-calendar.html", title: "世界の名前日カレンダー", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "国別の名前日を月日から検索", apiName: "International Nameday API", apiUrl: "https://nameday.abalin.net", icon: "ti-calendar" },
  { id: "icsdb-non-working-days", file: "tools/icsdb-non-working-days.html", title: "ICSDB 非稼働日ファイル", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "GitHub上の非稼働日ICSファイル候補を一覧", apiName: "icsdb", apiUrl: "https://github.com/gadael/icsdb", icon: "ti-calendar" },
  { id: "isdayoff", file: "tools/isdayoff.html", title: "isDayOff 稼働日判定", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "日付が稼働日・休日・短縮日かをコードで判定", apiName: "isDayOff", apiUrl: "https://isdayoff.ru", icon: "ti-calendar" },
  { id: "russian-calendar", file: "tools/russian-calendar.html", title: "Russian Work Calendar", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "ロシアの稼働日判定サービス実装例を確認", apiName: "work-calendar", apiUrl: "https://github.com/egno/work-calendar", icon: "ti-calendar" },
  { id: "the-calendar-api", file: "tools/the-calendar-api.html", title: "The Calendar API", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "祝日・スポーツ・金融カレンダーJSONのURLを組み立てる", apiName: "The Calendar", apiUrl: "https://the-calendar.net/api/", icon: "ti-calendar" },
  { id: "uk-bank-holidays", file: "tools/uk-bank-holidays.html", title: "英国バンクホリデー", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "GOV.UKの地域別バンクホリデーJSONを表示", apiName: "GOV.UK Bank Holidays", apiUrl: "https://www.gov.uk/bank-holidays.json", icon: "ti-calendar" },
  { id: "time", file: "tools/time.html", title: "時計", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "現在時刻を大きく表示するシンプルな時計", apiName: "ローカル時刻", apiUrl: "", icon: "ti-clock" },
  { id: "currency", file: "tools/currency_converter.html", title: "通貨換算", category: "為替・ツール系", categoryPath: ["為替・ツール系", "通貨・為替"],
    description: "指定した通貨間で金額を換算", apiName: "ExchangeRate-API", apiUrl: "https://www.exchangerate-api.com/", icon: "ti-currency-yen" },
  { id: "kawase", file: "tools/kawase.html", title: "為替レート", category: "為替・ツール系", categoryPath: ["為替・ツール系", "通貨・為替"],
    description: "通貨ペアの為替レートを取得", apiName: "exchangerate.host", apiUrl: "https://exchangerate.host/", icon: "ti-arrows-exchange" },
  { id: "qr", file: "tools/QR.html", title: "QRコードおみくじ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "生成・変換"],
    description: "ランダムなメッセージ入りQRコードを生成", apiName: "QR Server (goQR)", apiUrl: "https://goqr.me/api/", icon: "ti-qrcode" },
  { id: "translate", file: "tools/genngohonnyaku.html", title: "簡易翻訳", category: "為替・ツール系", categoryPath: ["為替・ツール系", "翻訳・言語"],
    description: "内蔵辞書で日本語↔英語を簡易翻訳（サンプル）", apiName: "ローカル辞書", apiUrl: "", icon: "ti-language" },
  { id: "tizu", file: "tools/tizu.html", title: "地図アプリ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "地図・住所"],
    description: "地図を表示し、クリック地点にマーカーを追加", apiName: "Leaflet / OpenStreetMap", apiUrl: "https://leafletjs.com/", icon: "ti-globe" },
  { id: "zipcode", file: "tools/zipcode.html", title: "郵便番号検索", category: "為替・ツール系", categoryPath: ["為替・ツール系", "地図・住所"],
    description: "郵便番号から住所を検索して表示", apiName: "ZipCloud API", apiUrl: "https://zipcloud.ibsnet.co.jp/doc/api", icon: "ti-qrcode" },
  { id: "postman-echo", file: "tools/postman-echo.html", title: "Postman Echo リクエスト検証", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "送信したGETパラメータを返すテストAPIでfetch結果を確認", apiName: "Postman Echo", apiUrl: "https://www.postman-echo.com", icon: "ti-search" },
  { id: "purgomalum", file: "tools/purgomalum.html", title: "PurgoMalum テキストフィルタ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "テキスト検証"],
    description: "入力テキストの不適切語を検出・置換する無料API", apiName: "PurgoMalum", apiUrl: "https://www.purgomalum.com/", icon: "ti-language" },
  { id: "beeceptor-echo", file: "tools/beeceptor-echo.html", title: "Beeceptor HTTP Echo", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "HTTPリクエストを送信し、エコー結果を確認できる", apiName: "Beeceptor HTTP Echo", apiUrl: "https://beeceptor.com/resources/http-echo/", icon: "ti-article" },
  { id: "brewpage", file: "tools/brewpage.html", title: "BrewPage HTML Publisher", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "HTMLを投稿して共有URLを取得（CORS時はcurlフォールバック）", apiName: "BrewPage API", apiUrl: "https://brewpage.app/api", icon: "ti-article" },
  { id: "ciprand", file: "tools/ciprand.html", title: "Ciprand Random String", category: "為替・ツール系", categoryPath: ["為替・ツール系", "生成・変換"],
    description: "セキュアなランダム文字列をAPIまたはWeb Cryptoで生成", apiName: "Ciprand", apiUrl: "https://github.com/polarspetroll/ciprand", icon: "ti-qrcode" },
  { id: "codex-compiler", file: "tools/codex-compiler.html", title: "CodeX Compiler Request Builder", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "オンラインコンパイラAPIへのリクエスト形状を確認", apiName: "CodeX", apiUrl: "https://github.com/Jaagrav/CodeX", icon: "ti-article" },
  { id: "cors-proxy", file: "tools/cors-proxy.html", title: "CORS Proxy URL Builder", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "CORS回避用プロキシURLを生成し取得を試行", apiName: "CORS Proxy", apiUrl: "https://github.com/burhanuday/cors-proxy", icon: "ti-search" },
  { id: "countapi", file: "tools/countapi.html", title: "CountAPI Counter", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "名前空間とキーでシンプルなカウンターを操作", apiName: "CountAPI", apiUrl: "https://countapi.xyz", icon: "ti-article" },
  { id: "extendsclass-json-storage", file: "tools/extendsclass-json-storage.html", title: "ExtendsClass JSON Storage", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "JSON保存API候補を試し、失敗時はlocalStorageに保存", apiName: "ExtendsClass JSON Storage", apiUrl: "https://extendsclass.com/json-storage.html", icon: "ti-article" },
  { id: "http2-pro", file: "tools/http2-pro.html", title: "HTTP2.Pro Checker", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "指定URLのHTTP/2対応チェックAPI候補を試行", apiName: "HTTP2.Pro", apiUrl: "https://http2.pro/doc/api", icon: "ti-search" },
  { id: "httpbin", file: "tools/httpbin.html", title: "Httpbin Request Lab", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "HTTPリクエスト/レスポンス検証用の定番APIを試す", apiName: "Httpbin", apiUrl: "https://httpbin.org/", icon: "ti-article" },
  { id: "httpbin-cloudflare", file: "tools/httpbin-cloudflare.html", title: "Httpbin Cloudflare Lab", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "Cloudflare版Httpbin互換API候補でGET echoを確認", apiName: "Httpbin Cloudflare", apiUrl: "https://cloudflare-quic.com/b/", icon: "ti-article" },
  { id: "icanhazepoch", file: "tools/icanhazepoch.html", title: "Icanhazepoch Clock", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "現在のUnix epoch秒をAPIまたはローカル時刻で表示", apiName: "Icanhazepoch", apiUrl: "https://icanhazepoch.com", icon: "ti-clock" },
  { id: "ifttt-connect", file: "tools/ifttt-connect.html", title: "IFTTT Connect API Notes", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "認証が必要なIFTTT Connect APIのリクエスト構造を確認", apiName: "IFTTT Connect API", apiUrl: "https://platform.ifttt.com/docs/connect_api", icon: "ti-article" },
  { id: "image-charts", file: "tools/image-charts.html", title: "Image-Charts Generator", category: "為替・ツール系", categoryPath: ["為替・ツール系", "生成・変換"],
    description: "URLパラメータで棒グラフ画像を生成", apiName: "Image-Charts", apiUrl: "https://documentation.image-charts.com/", icon: "ti-qrcode" },
  { id: "json2jsonp", file: "tools/json2jsonp.html", title: "JSON 2 JSONP Builder", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "JSON URLをJSONP呼び出し用URLへ変換", apiName: "JSON 2 JSONP", apiUrl: "https://json2jsonp.com/", icon: "ti-article" },
  { id: "keyvalue", file: "tools/keyvalue.html", title: "Keyvalue Store Demo", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "簡易key-valueストレージAPI候補を試す", apiName: "Keyvalue", apiUrl: "https://keyvalue.immanuel.co/", icon: "ti-article" },
  { id: "kroki", file: "tools/kroki.html", title: "Kroki Diagram Renderer", category: "為替・ツール系", categoryPath: ["為替・ツール系", "生成・変換"],
    description: "Mermaidなどのテキスト図を画像化", apiName: "Kroki", apiUrl: "https://kroki.io", icon: "ti-article" },
  { id: "lua-decompiler", file: "tools/lua-decompiler.html", title: "Lua Decompiler Request", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "Lua 5.1デコンパイラAPI候補のリクエスト形状を確認", apiName: "Lua Decompiler", apiUrl: "https://lua-decompiler.ferib.dev/", icon: "ti-article" },
  { id: "microenv", file: "tools/microenv.html", title: "MicroENV Fake REST", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "Fake REST API候補のリクエスト例を表示", apiName: "MicroENV", apiUrl: "https://microenv.com/", icon: "ti-article" },
  { id: "mocky", file: "tools/mocky.html", title: "Mocky Response Builder", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "任意JSONを返すモックURL作成手順を確認", apiName: "Mocky", apiUrl: "https://designer.mocky.io/", icon: "ti-article" },
  { id: "networkcalc", file: "tools/networkcalc.html", title: "NetworkCalc Subnet Helper", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "サブネットなどのネットワーク計算API候補を紹介", apiName: "NetworkCalc", apiUrl: "https://networkcalc.com/api/docs", icon: "ti-globe" },
  { id: "india-pincode", file: "tools/india-pincode.html", title: "インド郵便番号検索", category: "為替・ツール系", categoryPath: ["為替・ツール系", "地図・住所"],
    description: "インド郵便番号のサンプルデータで住所を検索", apiName: "Indian Pincode", apiUrl: "https://indianpincode.com/", icon: "ti-map" },
  { id: "file-io", file: "tools/file-io.html", title: "File.io 使い捨て共有", category: "為替・ツール系", categoryPath: ["為替・ツール系", "ファイル共有・保存"],
    description: "ファイルや短文を一時共有リンクに変換", apiName: "file.io", apiUrl: "https://www.file.io/", icon: "ti-upload" },
  { id: "fileup", file: "tools/fileup.html", title: "FileUp 共有アップローダー", category: "為替・ツール系", categoryPath: ["為替・ツール系", "ファイル共有・保存"],
    description: "期限と閲覧回数を決めてファイルを共有", apiName: "FileUp", apiUrl: "https://github.com/RealSinaSnp/FileUp", icon: "ti-file-upload" },
  { id: "pantry", file: "tools/pantry.html", title: "Pantry JSON ストレージ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "ファイル共有・保存"],
    description: "JSONをクラウドのバスケットに保存・取得", apiName: "Pantry", apiUrl: "https://getpantry.cloud/", icon: "ti-database" },
  { id: "null-pointer", file: "tools/null-pointer.html", title: "0x0.st 使い捨て共有", category: "為替・ツール系", categoryPath: ["為替・ツール系", "ファイル共有・保存"],
    description: "ファイルやURLを短い共有リンクに変換", apiName: "The Null Pointer", apiUrl: "https://0x0.st/", icon: "ti-link" },
  { id: "apicagent", file: "tools/apicagent.html", title: "User-Agent 診断器", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "UA文字列から端末やブラウザ情報を解析", apiName: "ApicAgent", apiUrl: "https://www.apicagent.com/docs", icon: "ti-user" },
  { id: "apis-guru", file: "tools/apis-guru.html", title: "API カタログ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "公開API定義を検索して件数を確認", apiName: "APIs.guru", apiUrl: "https://apis.guru/api-doc/", icon: "ti-search" },
  { id: "beeceptor", file: "tools/beeceptor.html", title: "Beeceptor モックAPI", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "モックエンドポイントの送受信を試す", apiName: "Beeceptor", apiUrl: "https://beeceptor.com/", icon: "ti-browser" },
  { id: "bored", file: "tools/bored.html", title: "Bored 予定提案", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "退屈しのぎのアクティビティをランダム提案", apiName: "Bored", apiUrl: "https://www.boredapi.com/", icon: "ti-mood-crazy-happy" },
  { id: "brewpage", file: "tools/brewpage.html", title: "BrewPage 公開ツール", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "HTMLやJSONを短縮URL付きで公開する手順を整理", apiName: "BrewPage", apiUrl: "https://brewpage.app/", icon: "ti-upload" },
  { id: "cdnjs", file: "tools/cdnjs.html", title: "CDNJS ライブラリ検索", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "CDNJSのライブラリ情報と配信URLを検索", apiName: "CDNJS", apiUrl: "https://cdnjs.com/api", icon: "ti-search" },
  { id: "changelogs-md", file: "tools/changelogs-md.html", title: "Changelogs.md チェッカー", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "changelogメタデータの到達性を確認", apiName: "Changelogs.md", apiUrl: "https://changelogs.md/", icon: "ti-article" },
  { id: "ciprand", file: "tools/ciprand.html", title: "乱数文字列ジェネレータ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "長さと件数を変えて乱数文字列を生成", apiName: "Ciprand", apiUrl: "https://github.com/polarspetroll/ciprand", icon: "ti-article" },
  { id: "cloudflare-trace", file: "tools/cloudflare-trace.html", title: "Cloudflare Trace", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "接続情報をtrace文字列で表示", apiName: "Cloudflare Trace", apiUrl: "https://github.com/fawazahmed0/cloudflare-trace-api", icon: "ti-globe" },
  { id: "codex", file: "tools/codex.html", title: "CodeX オンラインコンパイラ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "ランタイム別のコード送信と実行確認を整理", apiName: "Codex", apiUrl: "https://github.com/Jaagrav/CodeX", icon: "ti-browser" },

  /* ---------- エンタメ・おもしろ系（ジョーク/雑学/クイズ） ---------- */
  { id: "joke", file: "fun/joke.html", title: "海外ジョーク", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "海外のジョークを取得して日本語訳付きで表示", apiName: "Official Joke API", apiUrl: "https://github.com/15Dkatz/official_joke_api", icon: "ti-mood-crazy-happy" },
  { id: "animechan", file: "fun/animechan.html", title: "Animechan", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "意思決定・名言"],
    description: "アニメ引用をランダム取得して表示", apiName: "Animechan API", apiUrl: "https://animechan.io/", icon: "ti-quote" },
  { id: "anime-facts", file: "fun/anime-facts.html", title: "Anime Facts", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "アニメ作品の雑学と画像を取得", apiName: "Anime Facts REST API", apiUrl: "https://chandan-02.github.io/anime-facts-rest-api/", icon: "ti-bulb" },
  { id: "ohuzake", file: "fun/ohuzake.html", title: "ランダム雑学", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "ランダムな豆知識(雑学)を取得して表示", apiName: "Useless Facts", apiUrl: "https://uselessfacts.jsph.pl/", icon: "ti-bulb" },
  { id: "opentrivia", file: "fun/OpenTrivia.html", title: "アニメ・ゲームクイズ", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "クイズ・ゲーム"],
    description: "ジャンル別の4択クイズに挑戦", apiName: "Open Trivia DB", apiUrl: "https://opentdb.com/", icon: "ti-help" },
  { id: "yesno", file: "fun/YesNo.html", title: "Yes / No ディサイダー", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "意思決定・名言"],
    description: "Yes/No で迷いを決めてくれる意思決定器", apiName: "yesno.wtf", apiUrl: "https://yesno.wtf/", icon: "ti-thumb-up" },
  { id: "meigenn", file: "fun/meigenn.html", title: "名言メーカー", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "意思決定・名言"],
    description: "カテゴリ別の名言をランダム表示（サンプル）", apiName: "ローカルデータ", apiUrl: "", icon: "ti-quote" },
  { id: "useless", file: "fun/Useless.html", title: "ランダム雑学", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "雑学を取得して翻訳付きで表示", apiName: "Useless Facts / MyMemory Translation API / Unsplash Source", apiUrl: "https://uselessfacts.jsph.pl/", icon: "ti-bulb" },
  { id: "tai", file: "fun/tai.html", title: "Dynamic Typing Challenge", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "クイズ・ゲーム"],
    description: "ランダムな英文お題でタイピングに挑戦", apiName: "Quotable API", apiUrl: "https://api.quotable.io/", icon: "ti-device-gamepad-2" },
  { id: "sindan", file: "fun/sindan.html", title: "ブラック企業診断", category: "エンタメ・おもしろ系",
    description: "質問に答えてブラック企業適性を診断する", apiName: "ローカルデータ", apiUrl: "", icon: "ti-help" },
  { id: "zyouku", file: "fun/zyouku.html", title: "ランダムジョーク問題", category: "エンタメ・おもしろ系",
    description: "海外ジョークを日本語訳付きで出題するクイズ", apiName: "Official Joke API + Google Translate", apiUrl: "https://official-joke-api.appspot.com/", icon: "ti-mood-crazy-happy" },
  { id: "bored", file: "fun/bored.html", title: "Bored Activity Roulette", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "気分転換アクティビティを提案（API不可時はローカル候補）", apiName: "Bored API", apiUrl: "https://www.boredapi.com/", icon: "ti-mood-crazy-happy" },
  { id: "hipsum", file: "fun/hipsum.html", title: "Hipsum Text Generator", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "ヒップスター風ダミーテキストを生成", apiName: "Hipsum", apiUrl: "https://hipsum.co", icon: "ti-quote" },
];




