/* ============================================================
   fronted-v2 / catalog.js
   templates/ 内の各 WebAPI 紹介ページ(HTML)のメタデータ一覧。
   この配列が「一覧の唯一の定義元」。テンプレートを追加したら
   ここに1要素足すだけでサイドバーに反映される。

   テンプレートはジャンル別のサブフォルダに整理されている:
     templates/image/  画像・ビジュアル系
     templates/data/   データ・検索系
     templates/tools/  為替・ツール系
     templates/fun/    エンタメ・おもしろ系

   各要素のフィールド:
     id          … URLハッシュ・選択識別子に使う一意キー（ファイル名ベース）
     file        … templates/ からの相対パス（例 "image/dog-api.html"）。
                    iframe は ../templates/<file> を読む
     title       … サイドバー/ヘッダーに表示する名称
     category    … 旧形式のグループ名（後方互換用）
     categoryPath… サイドバーの階層分類（例 ["データ・検索系", "宇宙・天気"]）
     description … ヘッダーのサブテキスト（このページの説明）
     apiName     … 利用している外部API名
     apiUrl      … 関連する公式ページ（参考リンク）
     icon        … Tabler Icons のクラス名（例 "ti-dog"）
   ============================================================ */

window.CATALOG = [
  /* ---------- 画像・ビジュアル系（動物・キャラ・画像を取得） ---------- */
  { id: "3d", file: "image/3D.html", title: "多ジャンル3Dモデル召喚API", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "3D・アバター"],
    description: "ランダムな3Dモデルを読み込み、回転操作しながら閲覧できる", apiName: "Three.js GLTF サンプル", apiUrl: "https://threejs.org/", icon: "ti-cube" },
  { id: "dog-api", file: "image/dog-api.html", title: "Dog API", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "ランダムな犬の画像を取得。犬種フィルターも搭載", apiName: "Dog API", apiUrl: "https://dog.ceo/dog-api/", icon: "ti-dog" },
  { id: "cat-api", file: "image/cat-api.html", title: "The Cat API", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "ランダムな猫の画像と猫種データを取得", apiName: "The Cat API", apiUrl: "https://thecatapi.com/", icon: "ti-cat" },
  { id: "fox", file: "image/Fox.html", title: "Random Fox", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "ランダムなキツネの画像を取得", apiName: "RandomFox", apiUrl: "https://randomfox.ca/", icon: "ti-paw" },
  { id: "neko", file: "image/neko.html", title: "HTTP Cat", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "HTTP・ステータス画像"],
    description: "HTTPステータスコードを猫の画像で表示", apiName: "HTTP Cat", apiUrl: "https://http.cat/", icon: "ti-browser" },
  { id: "necos", file: "image/Necos.html", title: "Nekos.best", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "キャラクター画像"],
    description: "アニメ風のネコミミ画像ビューア", apiName: "Nekos.best", apiUrl: "https://nekos.best/", icon: "ti-mood-smile" },
  { id: "waifu", file: "image/Waifu.html", title: "Waifu Gallery", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "キャラクター画像"],
    description: "アニメキャラ画像のギャラリー", apiName: "Waifu.im", apiUrl: "https://waifu.im/", icon: "ti-sparkles" },
  { id: "kamo", file: "image/kamo.html", title: "アヒルで一息", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "ランダムなアヒルの画像で気分転換", apiName: "Random-d.uk", apiUrl: "https://random-d.uk/", icon: "ti-feather" },
  { id: "food", file: "image/food.html", title: "食べ物画像検索", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "食べ物画像"],
    description: "料理名でWikipediaの画像を検索して表示", apiName: "Wikipedia API", apiUrl: "https://www.mediawiki.org/wiki/API:Main_page", icon: "ti-tools-kitchen-2" },
  { id: "dance-proto", file: "image/dance-proto.html", title: "Dance Prototype", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "3D・アバター"],
    description: "GLTFモデルを読み込み、アニメーションを切り替えて再生", apiName: "Three.js GLTF サンプル", apiUrl: "https://threejs.org/", icon: "ti-cube" },
  { id: "oto", file: "image/oto.html", title: "Avatar Studio", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "3D・アバター"],
    description: "3DアバターにBGMとTTSを組み合わせたダンスビューア", apiName: "Three.js / Web Speech API", apiUrl: "https://threejs.org/", icon: "ti-sparkles" },

  /* ---------- データ・検索系（一覧/検索/詳細データを扱う） ---------- */
  { id: "anime", file: "data/anime.html", title: "アニメ図鑑", category: "データ・検索系", categoryPath: ["データ・検索系", "アニメ・カード"],
    description: "アニメをキーワード検索・ランキング表示", apiName: "Jikan API", apiUrl: "https://jikan.moe/", icon: "ti-movie" },
  { id: "jikan", file: "data/Jikan.html", title: "アニメ掲示板", category: "データ・検索系", categoryPath: ["データ・検索系", "アニメ・カード"],
    description: "アニメ情報を掲示板風に一覧表示", apiName: "Jikan API", apiUrl: "https://jikan.moe/", icon: "ti-message-circle" },
  { id: "poke", file: "data/Poke.html", title: "ポケモンガチャ", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "ランダムにポケモンを引いて図鑑表示", apiName: "PokeAPI", apiUrl: "https://pokeapi.co/", icon: "ti-device-gamepad-2" },
  { id: "akusyonn", file: "data/akusyonn.html", title: "ゲーム図鑑", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "無料PCゲームの一覧・情報を取得", apiName: "FreeToGame", apiUrl: "https://www.freetogame.com/api-doc", icon: "ti-device-gamepad" },
  { id: "applemusic", file: "data/applemusic.html", title: "Apple Music 検索", category: "データ・検索系", categoryPath: ["データ・検索系", "音楽・書籍"],
    description: "iTunes の楽曲をキーワード検索", apiName: "iTunes Search API", apiUrl: "https://performance-partners.apple.com/search-api", icon: "ti-music" },
  { id: "nasa", file: "data/nasa.html", title: "NASA 今日の天体", category: "データ・検索系", categoryPath: ["データ・検索系", "宇宙・天気"],
    description: "NASA APOD の天体写真をランダム表示", apiName: "NASA APOD", apiUrl: "https://api.nasa.gov/", icon: "ti-rocket" },
  { id: "utyu", file: "data/utyu.html", title: "NASA 近地天体", category: "データ・検索系", categoryPath: ["データ・検索系", "宇宙・天気"],
    description: "地球近傍小惑星(NEO)の観測ダッシュボード", apiName: "NASA NeoWs", apiUrl: "https://api.nasa.gov/", icon: "ti-planet" },
  { id: "wakusei", file: "data/wakusei.html", title: "惑星情報", category: "データ・検索系", categoryPath: ["データ・検索系", "宇宙・天気"],
    description: "太陽系の惑星データを選んで表示（サンプル）", apiName: "ローカルデータ", apiUrl: "https://ja.wikipedia.org/wiki/惑星", icon: "ti-globe" },
  { id: "burogu", file: "data/burogu.html", title: "ランダム記事ローダー", category: "データ・検索系", categoryPath: ["データ・検索系", "記事・プロフィール"],
    description: "ダミーの記事データをランダムに読み込んで表示", apiName: "JSONPlaceholder", apiUrl: "https://jsonplaceholder.typicode.com/", icon: "ti-article" },
  { id: "game", file: "data/game.html", title: "高評価ゲーム一覧", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "評価の高いゲームを一覧表示（APIキー必要）", apiName: "RAWG API", apiUrl: "https://rawg.io/apidocs", icon: "ti-trophy" },
  { id: "hon", file: "data/hon.html", title: "現代漫画検索", category: "データ・検索系", categoryPath: ["データ・検索系", "音楽・書籍"],
    description: "キーワードで書籍・漫画を検索して表紙を表示", apiName: "Open Library", apiUrl: "https://openlibrary.org/developers/api", icon: "ti-book" },
  { id: "randomuser", file: "data/index.html", title: "ランダムユーザー生成器", category: "データ・検索系", categoryPath: ["データ・検索系", "記事・プロフィール"],
    description: "ランダムなプロフィール(氏名/写真/住所)を生成", apiName: "Random User Generator", apiUrl: "https://randomuser.me/", icon: "ti-user" },
  { id: "cars", file: "data/Cars.html", title: "Car Explorer", category: "データ・検索系", categoryPath: ["データ・検索系", "乗り物・交通"],
    description: "メーカーとモデルを選んで車両情報と画像を検索", apiName: "NHTSA Vehicle API / Wikipedia API", apiUrl: "https://vpic.nhtsa.dot.gov/api/", icon: "ti-car" },
  { id: "yugio", file: "data/Yugio.html", title: "遊戯王カード図鑑", category: "データ・検索系", categoryPath: ["データ・検索系", "アニメ・カード"],
    description: "カード名・属性・種族で検索してランダム表示", apiName: "YGOPRODeck API / MyMemory Translation API", apiUrl: "https://db.ygoprodeck.com/api-guide/", icon: "ti-cards" },
  { id: "countrysearch", file: "data/countrySearch.html", title: "国情報検索", category: "データ・検索系", categoryPath: ["データ・検索系", "国・地域"],
    description: "国名から人口と首都情報を検索して表示", apiName: "CountriesNow API", apiUrl: "https://countriesnow.space/", icon: "ti-globe" },
  { id: "ip", file: "data/ip.html", title: "IP Geolocation Dashboard", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "IP位置情報データをダッシュボード形式で表示（サンプル）", apiName: "ローカルサンプルデータ", apiUrl: "", icon: "ti-user" },
  { id: "kabu", file: "data/kabu.html", title: "株価検索", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "銘柄コードを入力して株価と騰落率を取得", apiName: "Alpha Vantage", apiUrl: "https://www.alphavantage.co/documentation/", icon: "ti-currency-yen" },
  { id: "zero-x", file: "data/zero-x.html", title: "0x API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "DEXの価格見積もりやスワップAPIを入力キー付きで確認", apiName: "0x API", apiUrl: "https://0x.org/api", icon: "ti-currency-yen" },
  { id: "one-inch", file: "data/one-inch.html", title: "1inch API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "1inchのDEX集約APIをBearerキー入力式で試す", apiName: "1inch API", apiUrl: "https://1inch.io/api/", icon: "ti-currency-yen" },
  { id: "alpha-mossland", file: "data/alpha-mossland.html", title: "Alpha by Mossland", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "韓国暗号資産チャンネル由来の正規化データを表示", apiName: "Alpha by Mossland", apiUrl: "https://alpha.moss.land/developers", icon: "ti-search" },
  { id: "bitcambio", file: "data/bitcambio.html", title: "Bitcambio Public API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "ブラジル取引所の公開アセット情報を確認", apiName: "Bitcambio API", apiUrl: "https://nova.bitcambio.com.br/api/v3/docs#a-public", icon: "ti-currency-yen" },
  { id: "bitcoincharts", file: "data/bitcoincharts.html", title: "BitcoinCharts Markets", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "BitcoinChartsのマーケット一覧JSONを表示", apiName: "BitcoinCharts", apiUrl: "https://bitcoincharts.com/about/exchanges/", icon: "ti-currency-yen" },
  { id: "block-lottos", file: "data/block-lottos.html", title: "Block Lottos OpenAPI", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "オンチェーン抽選サービスのOpenAPI定義を読む", apiName: "Block Lottos", apiUrl: "https://blocklottos.com/openapi.json", icon: "ti-trophy" },
  { id: "btcnode-uk", file: "data/btcnode-uk.html", title: "btcnode.uk", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Bitcoinデータやx402課金エンドポイントのURLを確認", apiName: "btcnode.uk", apiUrl: "https://btcnode.uk", icon: "ti-currency-yen" },
  { id: "coincap", file: "data/coincap.html", title: "CoinCap API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "暗号資産の価格・時価総額・取引所データを取得", apiName: "CoinCap", apiUrl: "https://docs.coincap.io/", icon: "ti-currency-yen" },
  { id: "coindesk-bpi", file: "data/coindesk-bpi.html", title: "CoinDesk BPI", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Bitcoin Price Index系JSONを確認", apiName: "CoinDesk BPI", apiUrl: "https://old.coindesk.com/coindesk-api/", icon: "ti-currency-yen" },
  { id: "coingecko", file: "data/coingecko.html", title: "CoinGecko API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "BTC/ETHの複数通貨建て価格を取得", apiName: "CoinGecko API", apiUrl: "http://www.coingecko.com/api", icon: "ti-currency-yen" },
  { id: "coinlore", file: "data/coinlore.html", title: "CoinLore API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "公開ティッカーAPIから価格・出来高を一覧表示", apiName: "CoinLore", apiUrl: "https://www.coinlore.com/cryptocurrency-data-api", icon: "ti-currency-yen" },
  { id: "coinpaprika", file: "data/coinpaprika.html", title: "Coinpaprika API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "暗号資産マーケットデータをティッカー形式で表示", apiName: "Coinpaprika", apiUrl: "https://api.coinpaprika.com", icon: "ti-currency-yen" },
  { id: "coinstats", file: "data/coinstats.html", title: "CoinStats API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "暗号資産トラッカーAPIをキー入力式で確認", apiName: "CoinStats", apiUrl: "https://documenter.getpostman.com/view/5734027/RzZ6Hzr3?version=latest", icon: "ti-currency-yen" },
  { id: "cryptapi", file: "data/cryptapi.html", title: "CryptAPI", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "暗号資産決済APIの公開情報エンドポイントを確認", apiName: "CryptAPI", apiUrl: "https://docs.cryptapi.io/", icon: "ti-currency-yen" },
  { id: "cryptingup", file: "data/cryptingup.html", title: "CryptingUp", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "取引ペアやマーケットデータを取得", apiName: "CryptingUp", apiUrl: "https://www.cryptingup.com/apidoc/#introduction", icon: "ti-currency-yen" },
  { id: "cryptocompare", file: "data/cryptocompare.html", title: "CryptoCompare", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "BTC/ETHの価格を複数通貨で比較", apiName: "CryptoCompare", apiUrl: "https://www.cryptocompare.com/api#", icon: "ti-currency-yen" },
  { id: "cryptonator", file: "data/cryptonator.html", title: "Cryptonator", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "暗号資産為替レートAPIを確認", apiName: "Cryptonator", apiUrl: "https://www.cryptonator.com/api/", icon: "ti-currency-yen" },
  { id: "gemini", file: "data/gemini.html", title: "Gemini REST API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Gemini取引所の公開マーケットデータを取得", apiName: "Gemini REST API", apiUrl: "https://docs.gemini.com/rest-api/", icon: "ti-currency-yen" },
  { id: "localbitcoins", file: "data/localbitcoins.html", title: "LocalBitcoins API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "旧P2P取引API資料とサンプルデータを確認", apiName: "LocalBitcoins", apiUrl: "https://localbitcoins.com/api-docs/", icon: "ti-currency-yen" },
  { id: "mempool-space", file: "data/mempool-space.html", title: "Mempool.space API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Bitcoinの推奨手数料を取得", apiName: "Mempool.space", apiUrl: "https://mempool.space/api", icon: "ti-currency-yen" },
  { id: "mercado-bitcoin", file: "data/mercado-bitcoin.html", title: "Mercado Bitcoin API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "BTC/BRLの公開ティッカーを確認", apiName: "Mercado Bitcoin", apiUrl: "https://www.mercadobitcoin.com.br/api-doc/", icon: "ti-currency-yen" },
  { id: "messari", file: "data/messari.html", title: "Messari API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Messariの暗号資産データAPIをキー入力式で確認", apiName: "Messari API", apiUrl: "https://messari.io/api", icon: "ti-currency-yen" },
  { id: "nexchange", file: "data/nexchange.html", title: "Nexchange API", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "自動暗号資産交換サービスの通貨情報を確認", apiName: "Nexchange", apiUrl: "https://nexchange2.docs.apiary.io/", icon: "ti-currency-yen" },
  { id: "solana-json-rpc", file: "data/solana-json-rpc.html", title: "Solana JSON RPC", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Solana JSON-RPCへPOSTしてヘルスチェック", apiName: "Solana JSON RPC", apiUrl: "https://docs.solana.com/developing/clients/jsonrpc-api", icon: "ti-currency-yen" },
  { id: "zmok-ethereum-rpc", file: "data/zmok-ethereum-rpc.html", title: "ZMOK Ethereum RPC", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "Ethereum JSON-RPCプロバイダーURLを入力して確認", apiName: "ZMOK", apiUrl: "https://zmok.io", icon: "ti-currency-yen" },
  { id: "radar", file: "data/radar.html", title: "ADS-B Flight Radar", category: "データ・検索系", categoryPath: ["データ・検索系", "乗り物・交通"],
    description: "地図範囲内の航空機データを取得して可視化", apiName: "OpenSky Network API", apiUrl: "https://opensky-network.org/apidoc/rest.html", icon: "ti-rocket" },
  { id: "saiba", file: "data/saiba-.html", title: "Shodan Intelligence Terminal", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "IPアドレスの公開情報と開放ポートを調査", apiName: "Shodan API", apiUrl: "https://developer.shodan.io/api", icon: "ti-browser" },
  { id: "seibetu", file: "data/seibetu.html", title: "名前から性別を自動判別", category: "データ・検索系", categoryPath: ["データ・検索系", "人名・属性推定"],
    description: "ローマ字名から性別と確率を推定して表示", apiName: "Genderize.io", apiUrl: "https://genderize.io/", icon: "ti-user" },
  { id: "weather", file: "data/weather.html", title: "天気アプリ（気象庁版）", category: "データ・検索系", categoryPath: ["データ・検索系", "宇宙・天気"],
    description: "都道府県名から最新の天気予報を取得", apiName: "気象庁 予報JSON", apiUrl: "https://www.jma.go.jp/bosai/forecast/", icon: "ti-planet" },
  { id: "ai-dev-jobs", file: "data/ai-dev-jobs.html", title: "AI Dev Jobs API", category: "データ・検索系", categoryPath: ["データ・検索系", "求人・スキル"],
    description: "AI/MLエンジニア求人APIのOpenAPI定義を確認", apiName: "AI Dev Jobs", apiUrl: "https://aidevboard.com/openapi.yaml", icon: "ti-search" },
  { id: "arbeitnow", file: "data/arbeitnow.html", title: "Arbeitnow Job Board", category: "データ・検索系", categoryPath: ["データ・検索系", "求人・スキル"],
    description: "Europe/Remote求人をキーワードで絞り込んで表示", apiName: "Arbeitnow", apiUrl: "https://documenter.getpostman.com/view/18545278/UVJbJdKh", icon: "ti-article" },
  { id: "devitjobs-uk", file: "data/devitjobs-uk.html", title: "DevITjobs UK Feed", category: "データ・検索系", categoryPath: ["データ・検索系", "求人・スキル"],
    description: "UK開発者求人のXMLフィードを読み込んで表示", apiName: "DevITjobs UK", apiUrl: "https://devitjobs.uk/job_feed.xml", icon: "ti-article" },
  { id: "graphql-jobs", file: "data/graphql-jobs.html", title: "GraphQL Jobs API", category: "データ・検索系", categoryPath: ["データ・検索系", "求人・スキル"],
    description: "GraphQL求人APIへクエリをPOSTして確認", apiName: "GraphQL Jobs", apiUrl: "https://graphql.jobs/docs/api/", icon: "ti-search" },
  { id: "open-skills", file: "data/open-skills.html", title: "Open Skills API", category: "データ・検索系", categoryPath: ["データ・検索系", "求人・スキル"],
    description: "職種名やスキル名の候補を検索", apiName: "Open Skills", apiUrl: "https://github.com/workforce-data-initiative/skills-api/wiki/API-Overview", icon: "ti-user" },
  { id: "deepcode-ai", file: "data/deepcode-ai.html", title: "DeepCode AI", category: "データ・検索系", categoryPath: ["データ・検索系", "AI・機械学習"],
    description: "AIコードレビューサービスの公開情報を確認", apiName: "DeepCode AI", apiUrl: "https://www.deepcode.ai", icon: "ti-search" },
  { id: "exude-api", file: "data/exude-api.html", title: "EXUDE-API", category: "データ・検索系", categoryPath: ["データ・検索系", "AI・機械学習"],
    description: "英文テキストのストップワード除去を試す", apiName: "EXUDE-API", apiUrl: "http://uttesh.com/exude-api/", icon: "ti-language" },
  { id: "not-human-search", file: "data/not-human-search.html", title: "Not Human Search API", category: "データ・検索系", categoryPath: ["データ・検索系", "AI・機械学習"],
    description: "AIツール探索APIのOpenAPI定義を確認", apiName: "Not Human Search", apiUrl: "https://nothumansearch.ai/openapi.yaml", icon: "ti-search" },
  { id: "openvisionapi", file: "data/openvisionapi.html", title: "OpenVisionAPI", category: "データ・検索系", categoryPath: ["データ・検索系", "AI・機械学習"],
    description: "画像URLを渡すコンピュータビジョンAPIを確認", apiName: "OpenVisionAPI", apiUrl: "https://openvisionapi.com", icon: "ti-search" },
  { id: "tensorfeed", file: "data/tensorfeed.html", title: "TensorFeed API", category: "データ・検索系", categoryPath: ["データ・検索系", "AI・機械学習"],
    description: "AIニュース・モデル情報・サービス状態を取得", apiName: "TensorFeed", apiUrl: "https://tensorfeed.ai/developers", icon: "ti-article" },

  /* ---------- 為替・ツール系（実用ツール） ---------- */
  { id: "calendar", file: "tools/calendar.html", title: "カレンダー（祝日API付き）", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "祝日APIを参照して月間カレンダーを表示する", apiName: "Public Holidays API", apiUrl: "https://date.nager.at/", icon: "ti-calendar" },
  { id: "caldays", file: "tools/caldays.html", title: "CalDays 祝日API", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "APIキーを入力して国別の祝日データ取得を試す", apiName: "CalDays API", apiUrl: "https://caldays.com/api", icon: "ti-calendar" },
  { id: "church-calendar", file: "tools/church-calendar.html", title: "Church Calendar", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "指定日のカトリック典礼暦をJSONで確認", apiName: "Church Calendar API", apiUrl: "http://calapi.inadiutorium.cz/", icon: "ti-calendar" },
  { id: "czech-namedays", file: "tools/czech-namedays.html", title: "チェコ・スロバキア名前日", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "日付または名前からチェコ語・スロバキア語の名前日を検索", apiName: "Svátky API", apiUrl: "https://svatky.adresa.info", icon: "ti-calendar" },
  { id: "hebcal-converter", file: "tools/hebcal-converter.html", title: "Hebcal ヘブライ暦変換", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "グレゴリオ暦をヘブライ暦へ変換して表示", apiName: "Hebcal Developer APIs", apiUrl: "https://www.hebcal.com/home/developer-apis", icon: "ti-calendar" },
  { id: "lectserve", file: "tools/lectserve.html", title: "LectServe 朗読暦", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "プロテスタント系の朗読暦ページから見出しを抽出", apiName: "LectServe", apiUrl: "http://www.lectserve.com", icon: "ti-book" },
  { id: "nager-date", file: "tools/nager-date.html", title: "Nager.Date 世界祝日", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "国コードと年から世界各国の祝日一覧を取得", apiName: "Nager.Date", apiUrl: "https://date.nager.at", icon: "ti-calendar" },
  { id: "namedays-calendar", file: "tools/namedays-calendar.html", title: "世界の名前日カレンダー", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "国別の名前日を月日から検索", apiName: "International Nameday API", apiUrl: "https://nameday.abalin.net", icon: "ti-calendar" },
  { id: "icsdb-non-working-days", file: "tools/icsdb-non-working-days.html", title: "ICSDB 非稼働日ファイル", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "GitHub上の非稼働日ICSファイル候補を一覧", apiName: "icsdb", apiUrl: "https://github.com/gadael/icsdb", icon: "ti-calendar" },
  { id: "isdayoff", file: "tools/isdayoff.html", title: "isDayOff 稼働日判定", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "日付が稼働日・休日・短縮日かをコードで判定", apiName: "isDayOff", apiUrl: "https://isdayoff.ru", icon: "ti-calendar" },
  { id: "russian-calendar", file: "tools/russian-calendar.html", title: "Russian Work Calendar", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "ロシアの稼働日判定サービス実装例を確認", apiName: "work-calendar", apiUrl: "https://github.com/egno/work-calendar", icon: "ti-calendar" },
  { id: "the-calendar-api", file: "tools/the-calendar-api.html", title: "The Calendar API", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "祝日・スポーツ・金融カレンダーJSONのURLを組み立てる", apiName: "The Calendar", apiUrl: "https://the-calendar.net/api/", icon: "ti-calendar" },
  { id: "uk-bank-holidays", file: "tools/uk-bank-holidays.html", title: "英国バンクホリデー", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "GOV.UKの地域別バンクホリデーJSONを表示", apiName: "GOV.UK Bank Holidays", apiUrl: "https://www.gov.uk/bank-holidays.json", icon: "ti-calendar" },
  { id: "time", file: "tools/time.html", title: "時計", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "現在時刻を大きく表示するシンプルな時計", apiName: "ローカル時刻", apiUrl: "", icon: "ti-clock" },
  { id: "currency", file: "tools/currency_converter.html", title: "通貨換算", category: "為替・ツール系", categoryPath: ["為替・ツール系", "通貨・為替"],
    description: "指定した通貨間で金額を換算", apiName: "ExchangeRate-API", apiUrl: "https://www.exchangerate-api.com/", icon: "ti-currency-yen" },
  { id: "kawase", file: "tools/kawase.html", title: "為替レート", category: "為替・ツール系", categoryPath: ["為替・ツール系", "通貨・為替"],
    description: "通貨ペアの為替レートを取得", apiName: "exchangerate.host", apiUrl: "https://exchangerate.host/", icon: "ti-arrows-exchange" },
  { id: "qr", file: "tools/QR.html", title: "QRコードおみくじ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "生成・変換"],
    description: "ランダムなメッセージ入りQRコードを生成", apiName: "QR Server (goQR)", apiUrl: "https://goqr.me/api/", icon: "ti-qrcode" },
  { id: "translate", file: "tools/genngohonnyaku.html", title: "簡易翻訳", category: "為替・ツール系", categoryPath: ["為替・ツール系", "翻訳・言語"],
    description: "内蔵辞書で日本語↔英語を簡易翻訳（サンプル）", apiName: "ローカル辞書", apiUrl: "", icon: "ti-language" },
  { id: "tizu", file: "tools/tizu.html", title: "地図アプリ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "地図・住所"],
    description: "地図を表示し、クリック地点にマーカーを追加", apiName: "Leaflet / OpenStreetMap", apiUrl: "https://leafletjs.com/", icon: "ti-globe" },
  { id: "zipcode", file: "tools/zipcode.html", title: "郵便番号検索", category: "為替・ツール系", categoryPath: ["為替・ツール系", "地図・住所"],
    description: "郵便番号から住所を検索して表示", apiName: "ZipCloud API", apiUrl: "https://zipcloud.ibsnet.co.jp/doc/api", icon: "ti-qrcode" },
  { id: "file-io", file: "tools/file-io.html", title: "File.io 使い捨て共有", category: "為替・ツール系", categoryPath: ["為替・ツール系", "ファイル共有・保存"],
    description: "ファイルや短文を一時共有リンクに変換", apiName: "file.io", apiUrl: "https://www.file.io/", icon: "ti-upload" },
  { id: "fileup", file: "tools/fileup.html", title: "FileUp 共有アップローダー", category: "為替・ツール系", categoryPath: ["為替・ツール系", "ファイル共有・保存"],
    description: "期限と閲覧回数を決めてファイルを共有", apiName: "FileUp", apiUrl: "https://github.com/RealSinaSnp/FileUp", icon: "ti-file-upload" },
  { id: "pantry", file: "tools/pantry.html", title: "Pantry JSON ストレージ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "ファイル共有・保存"],
    description: "JSONをクラウドのバスケットに保存・取得", apiName: "Pantry", apiUrl: "https://getpantry.cloud/", icon: "ti-database" },
  { id: "null-pointer", file: "tools/null-pointer.html", title: "0x0.st 使い捨て共有", category: "為替・ツール系", categoryPath: ["為替・ツール系", "ファイル共有・保存"],
    description: "ファイルやURLを短い共有リンクに変換", apiName: "The Null Pointer", apiUrl: "https://0x0.st/", icon: "ti-link" },
  { id: "apicagent", file: "tools/apicagent.html", title: "User-Agent 診断器", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "UA文字列から端末やブラウザ情報を解析", apiName: "ApicAgent", apiUrl: "https://www.apicagent.com/docs", icon: "ti-user" },
  { id: "apis-guru", file: "tools/apis-guru.html", title: "API カタログ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "公開API定義を検索して件数を確認", apiName: "APIs.guru", apiUrl: "https://apis.guru/api-doc/", icon: "ti-search" },
  { id: "beeceptor", file: "tools/beeceptor.html", title: "Beeceptor モックAPI", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "モックエンドポイントの送受信を試す", apiName: "Beeceptor", apiUrl: "https://beeceptor.com/", icon: "ti-browser" },
  { id: "bored", file: "tools/bored.html", title: "Bored 予定提案", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "退屈しのぎのアクティビティをランダム提案", apiName: "Bored", apiUrl: "https://www.boredapi.com/", icon: "ti-mood-crazy-happy" },
  { id: "brewpage", file: "tools/brewpage.html", title: "BrewPage 公開ツール", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "HTMLやJSONを短縮URL付きで公開する手順を整理", apiName: "BrewPage", apiUrl: "https://brewpage.app/", icon: "ti-upload" },
  { id: "cdnjs", file: "tools/cdnjs.html", title: "CDNJS ライブラリ検索", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "CDNJSのライブラリ情報と配信URLを検索", apiName: "CDNJS", apiUrl: "https://cdnjs.com/api", icon: "ti-search" },
  { id: "changelogs-md", file: "tools/changelogs-md.html", title: "Changelogs.md チェッカー", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "changelogメタデータの到達性を確認", apiName: "Changelogs.md", apiUrl: "https://changelogs.md/", icon: "ti-article" },
  { id: "ciprand", file: "tools/ciprand.html", title: "乱数文字列ジェネレータ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "長さと件数を変えて乱数文字列を生成", apiName: "Ciprand", apiUrl: "https://github.com/polarspetroll/ciprand", icon: "ti-article" },
  { id: "cloudflare-trace", file: "tools/cloudflare-trace.html", title: "Cloudflare Trace", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "接続情報をtrace文字列で表示", apiName: "Cloudflare Trace", apiUrl: "https://github.com/fawazahmed0/cloudflare-trace-api", icon: "ti-globe" },
  { id: "codex", file: "tools/codex.html", title: "CodeX オンラインコンパイラ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "ランタイム別のコード送信と実行確認を整理", apiName: "Codex", apiUrl: "https://github.com/Jaagrav/CodeX", icon: "ti-browser" },

  /* ---------- エンタメ・おもしろ系（ジョーク/雑学/クイズ） ---------- */
  { id: "joke", file: "fun/joke.html", title: "海外ジョーク", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "海外のジョークを取得して日本語訳付きで表示", apiName: "Official Joke API", apiUrl: "https://github.com/15Dkatz/official_joke_api", icon: "ti-mood-crazy-happy" },
  { id: "ohuzake", file: "fun/ohuzake.html", title: "ランダム雑学", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "ランダムな豆知識(雑学)を取得して表示", apiName: "Useless Facts", apiUrl: "https://uselessfacts.jsph.pl/", icon: "ti-bulb" },
  { id: "opentrivia", file: "fun/OpenTrivia.html", title: "アニメ・ゲームクイズ", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "クイズ・ゲーム"],
    description: "ジャンル別の4択クイズに挑戦", apiName: "Open Trivia DB", apiUrl: "https://opentdb.com/", icon: "ti-help" },
  { id: "yesno", file: "fun/YesNo.html", title: "Yes / No ディサイダー", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "意思決定・名言"],
    description: "Yes/No で迷いを決めてくれる意思決定器", apiName: "yesno.wtf", apiUrl: "https://yesno.wtf/", icon: "ti-thumb-up" },
  { id: "meigenn", file: "fun/meigenn.html", title: "名言メーカー", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "意思決定・名言"],
    description: "カテゴリ別の名言をランダム表示（サンプル）", apiName: "ローカルデータ", apiUrl: "", icon: "ti-quote" },
  { id: "useless", file: "fun/Useless.html", title: "ランダム雑学", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "雑学を取得して翻訳付きで表示", apiName: "Useless Facts / MyMemory Translation API / Unsplash Source", apiUrl: "https://uselessfacts.jsph.pl/", icon: "ti-bulb" },
  { id: "tai", file: "fun/tai.html", title: "Dynamic Typing Challenge", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "クイズ・ゲーム"],
    description: "ランダムな英文お題でタイピングに挑戦", apiName: "Quotable API", apiUrl: "https://api.quotable.io/", icon: "ti-device-gamepad-2" },
];
