/* ============================================================
   fronted-v2 / catalog.js
   templates/ 内の各 WebAPI 紹介ページ(HTML)のメタデータ一覧。
   この配列が「一覧の唯一の定義元」。テンプレートを追加したら
   ここに1要素足すだけでサイドバーに反映される。

   テンプレートはジャンル別のサブフォルダに整理されている:
     templates/image/  画像・ビジュアル系
     templates/data/   データ・検索系
     templates/tools/  為替・ツール系
     templates/fun/    エンタメ・おもしろ系

   各要素のフィールド:
     id          … URLハッシュ・選択識別子に使う一意キー（ファイル名ベース）
     file        … templates/ からの相対パス（例 "image/dog-api.html"）。
                    iframe は ../templates/<file> を読む
     title       … サイドバー/ヘッダーに表示する名称
     category    … 旧形式のグループ名（後方互換用）
     categoryPath… サイドバーの階層分類（例 ["データ・検索系", "宇宙・天気"]）
     description … ヘッダーのサブテキスト（このページの説明）
     apiName     … 利用している外部API名
     apiUrl      … 関連する公式ページ（参考リンク）
     icon        … Tabler Icons のクラス名（例 "ti-dog"）
   ============================================================ */

window.CATALOG = [
  /* ---------- 画像・ビジュアル系（動物・キャラ・画像を取得） ---------- */
  { id: "3d", file: "image/3D.html", title: "多ジャンル3Dモデル召喚API", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "3D・アバター"],
    description: "ランダムな3Dモデルを読み込み、回転操作しながら閲覧できる", apiName: "Three.js GLTF サンプル", apiUrl: "https://threejs.org/", icon: "ti-cube" },
  { id: "dog-api", file: "image/dog-api.html", title: "Dog API", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "ランダムな犬の画像を取得。犬種フィルターも搭載", apiName: "Dog API", apiUrl: "https://dog.ceo/dog-api/", icon: "ti-dog" },
  { id: "cat-api", file: "image/cat-api.html", title: "The Cat API", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "ランダムな猫の画像と猫種データを取得", apiName: "The Cat API", apiUrl: "https://thecatapi.com/", icon: "ti-cat" },
  { id: "fox", file: "image/Fox.html", title: "Random Fox", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "ランダムなキツネの画像を取得", apiName: "RandomFox", apiUrl: "https://randomfox.ca/", icon: "ti-paw" },
  { id: "neko", file: "image/neko.html", title: "HTTP Cat", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "HTTP・ステータス画像"],
    description: "HTTPステータスコードを猫の画像で表示", apiName: "HTTP Cat", apiUrl: "https://http.cat/", icon: "ti-browser" },
  { id: "necos", file: "image/Necos.html", title: "Nekos.best", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "キャラクター画像"],
    description: "アニメ風のネコミミ画像ビューア", apiName: "Nekos.best", apiUrl: "https://nekos.best/", icon: "ti-mood-smile" },
  { id: "waifu", file: "image/Waifu.html", title: "Waifu Gallery", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "キャラクター画像"],
    description: "アニメキャラ画像のギャラリー", apiName: "Waifu.im", apiUrl: "https://waifu.im/", icon: "ti-sparkles" },
  { id: "kamo", file: "image/kamo.html", title: "アヒルで一息", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "動物画像"],
    description: "ランダムなアヒルの画像で気分転換", apiName: "Random-d.uk", apiUrl: "https://random-d.uk/", icon: "ti-feather" },
  { id: "food", file: "image/food.html", title: "食べ物画像検索", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "食べ物画像"],
    description: "料理名でWikipediaの画像を検索して表示", apiName: "Wikipedia API", apiUrl: "https://www.mediawiki.org/wiki/API:Main_page", icon: "ti-tools-kitchen-2" },
  { id: "dance-proto", file: "image/dance-proto.html", title: "Dance Prototype", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "3D・アバター"],
    description: "GLTFモデルを読み込み、アニメーションを切り替えて再生", apiName: "Three.js GLTF サンプル", apiUrl: "https://threejs.org/", icon: "ti-cube" },
  { id: "oto", file: "image/oto.html", title: "Avatar Studio", category: "画像・ビジュアル系", categoryPath: ["画像・ビジュアル系", "3D・アバター"],
    description: "3DアバターにBGMとTTSを組み合わせたダンスビューア", apiName: "Three.js / Web Speech API", apiUrl: "https://threejs.org/", icon: "ti-sparkles" },

  /* ---------- データ・検索系（一覧/検索/詳細データを扱う） ---------- */
  { id: "anime", file: "data/anime.html", title: "アニメ図鑑", category: "データ・検索系", categoryPath: ["データ・検索系", "アニメ・カード"],
    description: "アニメをキーワード検索・ランキング表示", apiName: "Jikan API", apiUrl: "https://jikan.moe/", icon: "ti-movie" },
  { id: "jikan", file: "data/Jikan.html", title: "アニメ掲示板", category: "データ・検索系", categoryPath: ["データ・検索系", "アニメ・カード"],
    description: "アニメ情報を掲示板風に一覧表示", apiName: "Jikan API", apiUrl: "https://jikan.moe/", icon: "ti-message-circle" },
  { id: "poke", file: "data/Poke.html", title: "ポケモンガチャ", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "ランダムにポケモンを引いて図鑑表示", apiName: "PokeAPI", apiUrl: "https://pokeapi.co/", icon: "ti-device-gamepad-2" },
  { id: "akusyonn", file: "data/akusyonn.html", title: "ゲーム図鑑", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "無料PCゲームの一覧・情報を取得", apiName: "FreeToGame", apiUrl: "https://www.freetogame.com/api-doc", icon: "ti-device-gamepad" },
  { id: "applemusic", file: "data/applemusic.html", title: "Apple Music 検索", category: "データ・検索系", categoryPath: ["データ・検索系", "音楽・書籍"],
    description: "iTunes の楽曲をキーワード検索", apiName: "iTunes Search API", apiUrl: "https://performance-partners.apple.com/search-api", icon: "ti-music" },
  { id: "nasa", file: "data/nasa.html", title: "NASA 今日の天体", category: "データ・検索系", categoryPath: ["データ・検索系", "宇宙・天気"],
    description: "NASA APOD の天体写真をランダム表示", apiName: "NASA APOD", apiUrl: "https://api.nasa.gov/", icon: "ti-rocket" },
  { id: "utyu", file: "data/utyu.html", title: "NASA 近地天体", category: "データ・検索系", categoryPath: ["データ・検索系", "宇宙・天気"],
    description: "地球近傍小惑星(NEO)の観測ダッシュボード", apiName: "NASA NeoWs", apiUrl: "https://api.nasa.gov/", icon: "ti-planet" },
  { id: "wakusei", file: "data/wakusei.html", title: "惑星情報", category: "データ・検索系", categoryPath: ["データ・検索系", "宇宙・天気"],
    description: "太陽系の惑星データを選んで表示（サンプル）", apiName: "ローカルデータ", apiUrl: "https://ja.wikipedia.org/wiki/惑星", icon: "ti-globe" },
  { id: "burogu", file: "data/burogu.html", title: "ランダム記事ローダー", category: "データ・検索系", categoryPath: ["データ・検索系", "記事・プロフィール"],
    description: "ダミーの記事データをランダムに読み込んで表示", apiName: "JSONPlaceholder", apiUrl: "https://jsonplaceholder.typicode.com/", icon: "ti-article" },
  { id: "game", file: "data/game.html", title: "高評価ゲーム一覧", category: "データ・検索系", categoryPath: ["データ・検索系", "ゲーム・キャラクター"],
    description: "評価の高いゲームを一覧表示（APIキー必要）", apiName: "RAWG API", apiUrl: "https://rawg.io/apidocs", icon: "ti-trophy" },
  { id: "hon", file: "data/hon.html", title: "現代漫画検索", category: "データ・検索系", categoryPath: ["データ・検索系", "音楽・書籍"],
    description: "キーワードで書籍・漫画を検索して表紙を表示", apiName: "Open Library", apiUrl: "https://openlibrary.org/developers/api", icon: "ti-book" },
  { id: "randomuser", file: "data/index.html", title: "ランダムユーザー生成器", category: "データ・検索系", categoryPath: ["データ・検索系", "記事・プロフィール"],
    description: "ランダムなプロフィール(氏名/写真/住所)を生成", apiName: "Random User Generator", apiUrl: "https://randomuser.me/", icon: "ti-user" },
  { id: "cars", file: "data/Cars.html", title: "Car Explorer", category: "データ・検索系", categoryPath: ["データ・検索系", "乗り物・交通"],
    description: "メーカーとモデルを選んで車両情報と画像を検索", apiName: "NHTSA Vehicle API / Wikipedia API", apiUrl: "https://vpic.nhtsa.dot.gov/api/", icon: "ti-car" },
  { id: "yugio", file: "data/Yugio.html", title: "遊戯王カード図鑑", category: "データ・検索系", categoryPath: ["データ・検索系", "アニメ・カード"],
    description: "カード名・属性・種族で検索してランダム表示", apiName: "YGOPRODeck API / MyMemory Translation API", apiUrl: "https://db.ygoprodeck.com/api-guide/", icon: "ti-cards" },
  { id: "countrysearch", file: "data/countrySearch.html", title: "国情報検索", category: "データ・検索系", categoryPath: ["データ・検索系", "国・地域"],
    description: "国名から人口と首都情報を検索して表示", apiName: "CountriesNow API", apiUrl: "https://countriesnow.space/", icon: "ti-globe" },
  { id: "ip", file: "data/ip.html", title: "IP Geolocation Dashboard", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "IP位置情報データをダッシュボード形式で表示（サンプル）", apiName: "ローカルサンプルデータ", apiUrl: "", icon: "ti-user" },
  { id: "kabu", file: "data/kabu.html", title: "株価検索", category: "データ・検索系", categoryPath: ["データ・検索系", "金融・マーケット"],
    description: "銘柄コードを入力して株価と騰落率を取得", apiName: "Alpha Vantage", apiUrl: "https://www.alphavantage.co/documentation/", icon: "ti-currency-yen" },
  { id: "radar", file: "data/radar.html", title: "ADS-B Flight Radar", category: "データ・検索系", categoryPath: ["データ・検索系", "乗り物・交通"],
    description: "地図範囲内の航空機データを取得して可視化", apiName: "OpenSky Network API", apiUrl: "https://opensky-network.org/apidoc/rest.html", icon: "ti-rocket" },
  { id: "saiba", file: "data/saiba-.html", title: "Shodan Intelligence Terminal", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "IPアドレスの公開情報と開放ポートを調査", apiName: "Shodan API", apiUrl: "https://developer.shodan.io/api", icon: "ti-browser" },
  { id: "seibetu", file: "data/seibetu.html", title: "名前から性別を自動判別", category: "データ・検索系", categoryPath: ["データ・検索系", "人名・属性推定"],
    description: "ローマ字名から性別と確率を推定して表示", apiName: "Genderize.io", apiUrl: "https://genderize.io/", icon: "ti-user" },
  { id: "agify", file: "data/agify.html", title: "Agify.io 年齢推定", category: "データ・検索系", categoryPath: ["データ・検索系", "人名・属性推定"],
    description: "名前と国コードから推定年齢と参照件数を取得", apiName: "Agify.io", apiUrl: "https://agify.io/", icon: "ti-user" },
  { id: "weather", file: "data/weather.html", title: "天気アプリ（気象庁版）", category: "データ・検索系", categoryPath: ["データ・検索系", "宇宙・天気"],
    description: "都道府県名から最新の天気予報を取得", apiName: "気象庁 予報JSON", apiUrl: "https://www.jma.go.jp/bosai/forecast/", icon: "ti-planet" },
  { id: "24-pull-requests", file: "data/24-pull-requests.html", title: "24 Pull Requests Explorer", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "OSS貢献促進サービスのプロジェクト一覧やPR統計を取得", apiName: "24 Pull Requests API", apiUrl: "https://24pullrequests.com/api", icon: "ti-article" },
  { id: "api-gratis", file: "data/api-gratis.html", title: "API Grátis チェッカー", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "API Grátis公式URLの到達状況と仕様確認メモを表示", apiName: "API Grátis", apiUrl: "https://apigratis.com.br/", icon: "ti-search" },
  { id: "apicagent", file: "data/apicagent.html", title: "ApicAgent User-Agent 解析", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "User-Agent文字列を解析してブラウザ・OS・端末情報を表示", apiName: "ApicAgent", apiUrl: "https://www.apicagent.com/docs", icon: "ti-browser" },
  { id: "apis-guru", file: "data/apis-guru.html", title: "APIs.guru Directory Explorer", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "OpenAPIディレクトリのメトリクスとプロバイダ一覧を検索", apiName: "APIs.guru Directory API", apiUrl: "https://apis.guru/api-doc/", icon: "ti-search" },
  { id: "cdnjs", file: "data/cdnjs.html", title: "CDNJS Library Finder", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "cdnjsの公開APIからライブラリ情報とCDN URLを検索", apiName: "CDNJS API", apiUrl: "https://api.cdnjs.com/libraries/jquery", icon: "ti-search" },
  { id: "changelogs-md", file: "data/changelogs-md.html", title: "Changelogs.md Search", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "OSSライブラリのchangelog検索結果を取得して表示", apiName: "Changelogs.md", apiUrl: "https://changelogs.md", icon: "ti-article" },
  { id: "cloudflare-trace", file: "data/cloudflare-trace.html", title: "Cloudflare Trace Viewer", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "Cloudflare traceからIP・国・HTTP/TLS情報を取得", apiName: "Cloudflare Trace API", apiUrl: "https://github.com/fawazahmed0/cloudflare-trace-api", icon: "ti-browser" },
  { id: "digitalocean-status", file: "data/digitalocean-status.html", title: "DigitalOcean Status", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "DigitalOceanの全体状態とコンポーネント状態を取得", apiName: "DigitalOcean Status API", apiUrl: "https://status.digitalocean.com/api", icon: "ti-browser" },
  { id: "domainsdb", file: "data/domainsdb.html", title: "DomainDb Search", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "キーワードを含むドメイン名を検索", apiName: "DomainDb Info", apiUrl: "https://api.domainsdb.info/", icon: "ti-search" },
  { id: "downstatus", file: "data/downstatus.html", title: "DownStatus Monitor", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "外部サービスの稼働状況確認API候補を表示", apiName: "DownStatus", apiUrl: "https://isitdownstatus.com", icon: "ti-browser" },
  { id: "host-t-dns", file: "data/host-t-dns.html", title: "host-t DNS Query", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "HTTP GETでDNS問い合わせURLを作成し取得を試行", apiName: "host-t.com", apiUrl: "https://host-t.com", icon: "ti-globe" },
  { id: "icanhazip", file: "data/icanhazip.html", title: "Icanhazip Viewer", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "アクセス元のグローバルIPアドレスを取得", apiName: "Icanhazip", apiUrl: "https://major.io/icanhazip-com-faq/", icon: "ti-globe" },
  { id: "ip-fast", file: "data/ip-fast.html", title: "ip-fast Lookup", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "IPアドレス・国・都市情報を取得", apiName: "ip-fast.com", apiUrl: "https://ip-fast.com/docs/", icon: "ti-globe" },
  { id: "ipify", file: "data/ipify.html", title: "IPify Viewer", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "現在のグローバルIPアドレスをJSONで取得", apiName: "IPify", apiUrl: "https://www.ipify.org/", icon: "ti-globe" },
  { id: "ipinfo", file: "data/ipinfo.html", title: "IPinfo Lite", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "IPの地域・組織情報を取得（制限時はフォールバック）", apiName: "IPinfo", apiUrl: "https://ipinfo.io/developers", icon: "ti-globe" },
  { id: "my-ip", file: "data/my-ip.html", title: "MY IP Lookup", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "MY IP APIからIPアドレス情報を取得", apiName: "MY IP", apiUrl: "https://www.myip.com/api-docs/", icon: "ti-globe" },
  { id: "isitdownstatus", file: "data/isitdownstatus.html", title: "isitdownstatus Checker", category: "データ・検索系", categoryPath: ["データ・検索系", "ネットワーク・セキュリティ"],
    description: "Webサイトやサービスのダウン状態確認API候補", apiName: "isitdownstatus", apiUrl: "https://isitdownstatus.com", icon: "ti-browser" },
  { id: "jsdelivr", file: "data/jsdelivr.html", title: "jsDelivr Package Info", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "npmパッケージのCDNファイル情報を取得", apiName: "jsDelivr Data API", apiUrl: "https://github.com/jsdelivr/data.jsdelivr.com", icon: "ti-search" },
  { id: "license-api", file: "data/license-api.html", title: "License API Lookup", category: "データ・検索系", categoryPath: ["データ・検索系", "開発・OSS"],
    description: "OSSライセンス情報API候補を取得またはフォールバック表示", apiName: "License-API", apiUrl: "https://github.com/cmccandless/license-api/blob/master/README.md", icon: "ti-article" },
  { id: "nationalize", file: "data/nationalize.html", title: "Nationalize.io Predictor", category: "データ・検索系", categoryPath: ["データ・検索系", "人名・属性推定"],
    description: "名前から国籍候補と確率を推定", apiName: "Nationalize.io", apiUrl: "https://nationalize.io", icon: "ti-user" },

  /* ---------- 為替・ツール系（実用ツール） ---------- */
  { id: "calendar", file: "tools/calendar.html", title: "カレンダー（祝日API付き）", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "祝日APIを参照して月間カレンダーを表示する", apiName: "Public Holidays API", apiUrl: "https://date.nager.at/", icon: "ti-calendar" },
  { id: "time", file: "tools/time.html", title: "時計", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "現在時刻を大きく表示するシンプルな時計", apiName: "ローカル時刻", apiUrl: "", icon: "ti-clock" },
  { id: "currency", file: "tools/currency_converter.html", title: "通貨換算", category: "為替・ツール系", categoryPath: ["為替・ツール系", "通貨・為替"],
    description: "指定した通貨間で金額を換算", apiName: "ExchangeRate-API", apiUrl: "https://www.exchangerate-api.com/", icon: "ti-currency-yen" },
  { id: "kawase", file: "tools/kawase.html", title: "為替レート", category: "為替・ツール系", categoryPath: ["為替・ツール系", "通貨・為替"],
    description: "通貨ペアの為替レートを取得", apiName: "exchangerate.host", apiUrl: "https://exchangerate.host/", icon: "ti-arrows-exchange" },
  { id: "qr", file: "tools/QR.html", title: "QRコードおみくじ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "生成・変換"],
    description: "ランダムなメッセージ入りQRコードを生成", apiName: "QR Server (goQR)", apiUrl: "https://goqr.me/api/", icon: "ti-qrcode" },
  { id: "translate", file: "tools/genngohonnyaku.html", title: "簡易翻訳", category: "為替・ツール系", categoryPath: ["為替・ツール系", "翻訳・言語"],
    description: "内蔵辞書で日本語↔英語を簡易翻訳（サンプル）", apiName: "ローカル辞書", apiUrl: "", icon: "ti-language" },
  { id: "tizu", file: "tools/tizu.html", title: "地図アプリ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "地図・住所"],
    description: "地図を表示し、クリック地点にマーカーを追加", apiName: "Leaflet / OpenStreetMap", apiUrl: "https://leafletjs.com/", icon: "ti-globe" },
  { id: "zipcode", file: "tools/zipcode.html", title: "郵便番号検索", category: "為替・ツール系", categoryPath: ["為替・ツール系", "地図・住所"],
    description: "郵便番号から住所を検索して表示", apiName: "ZipCloud API", apiUrl: "https://zipcloud.ibsnet.co.jp/doc/api", icon: "ti-qrcode" },
  { id: "postman-echo", file: "tools/postman-echo.html", title: "Postman Echo リクエスト検証", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "送信したGETパラメータを返すテストAPIでfetch結果を確認", apiName: "Postman Echo", apiUrl: "https://www.postman-echo.com", icon: "ti-search" },
  { id: "purgomalum", file: "tools/purgomalum.html", title: "PurgoMalum テキストフィルタ", category: "為替・ツール系", categoryPath: ["為替・ツール系", "テキスト検証"],
    description: "入力テキストの不適切語を検出・置換する無料API", apiName: "PurgoMalum", apiUrl: "https://www.purgomalum.com/", icon: "ti-language" },
  { id: "beeceptor-echo", file: "tools/beeceptor-echo.html", title: "Beeceptor HTTP Echo", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "HTTPリクエストを送信し、エコー結果を確認できる", apiName: "Beeceptor HTTP Echo", apiUrl: "https://beeceptor.com/resources/http-echo/", icon: "ti-article" },
  { id: "brewpage", file: "tools/brewpage.html", title: "BrewPage HTML Publisher", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "HTMLを投稿して共有URLを取得（CORS時はcurlフォールバック）", apiName: "BrewPage API", apiUrl: "https://brewpage.app/api", icon: "ti-article" },
  { id: "ciprand", file: "tools/ciprand.html", title: "Ciprand Random String", category: "為替・ツール系", categoryPath: ["為替・ツール系", "生成・変換"],
    description: "セキュアなランダム文字列をAPIまたはWeb Cryptoで生成", apiName: "Ciprand", apiUrl: "https://github.com/polarspetroll/ciprand", icon: "ti-qrcode" },
  { id: "codex-compiler", file: "tools/codex-compiler.html", title: "CodeX Compiler Request Builder", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "オンラインコンパイラAPIへのリクエスト形状を確認", apiName: "CodeX", apiUrl: "https://github.com/Jaagrav/CodeX", icon: "ti-article" },
  { id: "cors-proxy", file: "tools/cors-proxy.html", title: "CORS Proxy URL Builder", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "CORS回避用プロキシURLを生成し取得を試行", apiName: "CORS Proxy", apiUrl: "https://github.com/burhanuday/cors-proxy", icon: "ti-search" },
  { id: "countapi", file: "tools/countapi.html", title: "CountAPI Counter", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "名前空間とキーでシンプルなカウンターを操作", apiName: "CountAPI", apiUrl: "https://countapi.xyz", icon: "ti-article" },
  { id: "extendsclass-json-storage", file: "tools/extendsclass-json-storage.html", title: "ExtendsClass JSON Storage", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "JSON保存API候補を試し、失敗時はlocalStorageに保存", apiName: "ExtendsClass JSON Storage", apiUrl: "https://extendsclass.com/json-storage.html", icon: "ti-article" },
  { id: "http2-pro", file: "tools/http2-pro.html", title: "HTTP2.Pro Checker", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "指定URLのHTTP/2対応チェックAPI候補を試行", apiName: "HTTP2.Pro", apiUrl: "https://http2.pro/doc/api", icon: "ti-search" },
  { id: "httpbin", file: "tools/httpbin.html", title: "Httpbin Request Lab", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "HTTPリクエスト/レスポンス検証用の定番APIを試す", apiName: "Httpbin", apiUrl: "https://httpbin.org/", icon: "ti-article" },
  { id: "httpbin-cloudflare", file: "tools/httpbin-cloudflare.html", title: "Httpbin Cloudflare Lab", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "Cloudflare版Httpbin互換API候補でGET echoを確認", apiName: "Httpbin Cloudflare", apiUrl: "https://cloudflare-quic.com/b/", icon: "ti-article" },
  { id: "icanhazepoch", file: "tools/icanhazepoch.html", title: "Icanhazepoch Clock", category: "為替・ツール系", categoryPath: ["為替・ツール系", "日付・時刻"],
    description: "現在のUnix epoch秒をAPIまたはローカル時刻で表示", apiName: "Icanhazepoch", apiUrl: "https://icanhazepoch.com", icon: "ti-clock" },
  { id: "ifttt-connect", file: "tools/ifttt-connect.html", title: "IFTTT Connect API Notes", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "認証が必要なIFTTT Connect APIのリクエスト構造を確認", apiName: "IFTTT Connect API", apiUrl: "https://platform.ifttt.com/docs/connect_api", icon: "ti-article" },
  { id: "image-charts", file: "tools/image-charts.html", title: "Image-Charts Generator", category: "為替・ツール系", categoryPath: ["為替・ツール系", "生成・変換"],
    description: "URLパラメータで棒グラフ画像を生成", apiName: "Image-Charts", apiUrl: "https://documentation.image-charts.com/", icon: "ti-qrcode" },
  { id: "json2jsonp", file: "tools/json2jsonp.html", title: "JSON 2 JSONP Builder", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "JSON URLをJSONP呼び出し用URLへ変換", apiName: "JSON 2 JSONP", apiUrl: "https://json2jsonp.com/", icon: "ti-article" },
  { id: "keyvalue", file: "tools/keyvalue.html", title: "Keyvalue Store Demo", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "簡易key-valueストレージAPI候補を試す", apiName: "Keyvalue", apiUrl: "https://keyvalue.immanuel.co/", icon: "ti-article" },
  { id: "kroki", file: "tools/kroki.html", title: "Kroki Diagram Renderer", category: "為替・ツール系", categoryPath: ["為替・ツール系", "生成・変換"],
    description: "Mermaidなどのテキスト図を画像化", apiName: "Kroki", apiUrl: "https://kroki.io", icon: "ti-article" },
  { id: "lua-decompiler", file: "tools/lua-decompiler.html", title: "Lua Decompiler Request", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "Lua 5.1デコンパイラAPI候補のリクエスト形状を確認", apiName: "Lua Decompiler", apiUrl: "https://lua-decompiler.ferib.dev/", icon: "ti-article" },
  { id: "microenv", file: "tools/microenv.html", title: "MicroENV Fake REST", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "Fake REST API候補のリクエスト例を表示", apiName: "MicroENV", apiUrl: "https://microenv.com/", icon: "ti-article" },
  { id: "mocky", file: "tools/mocky.html", title: "Mocky Response Builder", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "任意JSONを返すモックURL作成手順を確認", apiName: "Mocky", apiUrl: "https://designer.mocky.io/", icon: "ti-article" },
  { id: "networkcalc", file: "tools/networkcalc.html", title: "NetworkCalc Subnet Helper", category: "為替・ツール系", categoryPath: ["為替・ツール系", "開発・検証"],
    description: "サブネットなどのネットワーク計算API候補を紹介", apiName: "NetworkCalc", apiUrl: "https://networkcalc.com/api/docs", icon: "ti-globe" },

  /* ---------- エンタメ・おもしろ系（ジョーク/雑学/クイズ） ---------- */
  { id: "joke", file: "fun/joke.html", title: "海外ジョーク", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "海外のジョークを取得して日本語訳付きで表示", apiName: "Official Joke API", apiUrl: "https://github.com/15Dkatz/official_joke_api", icon: "ti-mood-crazy-happy" },
  { id: "ohuzake", file: "fun/ohuzake.html", title: "ランダム雑学", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "ランダムな豆知識(雑学)を取得して表示", apiName: "Useless Facts", apiUrl: "https://uselessfacts.jsph.pl/", icon: "ti-bulb" },
  { id: "opentrivia", file: "fun/OpenTrivia.html", title: "アニメ・ゲームクイズ", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "クイズ・ゲーム"],
    description: "ジャンル別の4択クイズに挑戦", apiName: "Open Trivia DB", apiUrl: "https://opentdb.com/", icon: "ti-help" },
  { id: "yesno", file: "fun/YesNo.html", title: "Yes / No ディサイダー", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "意思決定・名言"],
    description: "Yes/No で迷いを決めてくれる意思決定器", apiName: "yesno.wtf", apiUrl: "https://yesno.wtf/", icon: "ti-thumb-up" },
  { id: "meigenn", file: "fun/meigenn.html", title: "名言メーカー", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "意思決定・名言"],
    description: "カテゴリ別の名言をランダム表示（サンプル）", apiName: "ローカルデータ", apiUrl: "", icon: "ti-quote" },
  { id: "useless", file: "fun/Useless.html", title: "ランダム雑学", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "雑学を取得して翻訳付きで表示", apiName: "Useless Facts / MyMemory Translation API / Unsplash Source", apiUrl: "https://uselessfacts.jsph.pl/", icon: "ti-bulb" },
  { id: "tai", file: "fun/tai.html", title: "Dynamic Typing Challenge", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "クイズ・ゲーム"],
    description: "ランダムな英文お題でタイピングに挑戦", apiName: "Quotable API", apiUrl: "https://api.quotable.io/", icon: "ti-device-gamepad-2" },
  { id: "bored", file: "fun/bored.html", title: "Bored Activity Roulette", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "気分転換アクティビティを提案（API不可時はローカル候補）", apiName: "Bored API", apiUrl: "https://www.boredapi.com/", icon: "ti-mood-crazy-happy" },
  { id: "hipsum", file: "fun/hipsum.html", title: "Hipsum Text Generator", category: "エンタメ・おもしろ系", categoryPath: ["エンタメ・おもしろ系", "ジョーク・雑学"],
    description: "ヒップスター風ダミーテキストを生成", apiName: "Hipsum", apiUrl: "https://hipsum.co", icon: "ti-quote" },
];
